### ISSUE TITLE
What's the correct segmentation label match the organ name in Wholebody ct segmentation pre-trained model?

### ISSUE THREAD

**Issue by ytl0623** [wasserth/TotalSegmentator#115]
Hi, I used to execute inference with TotalSegmentator high res. pre-trained model.

But after I finished the process the output image (.nii) is NOT match the organ list (like picture below).

The organ list (I supposed) is sort by A-Z, but the real output image is red text.
![image](https://user-images.githubusercontent.com/55120101/234814010-02620b8a-c886-4a12-8b24-2f8a8a4199e9.png)

So, what is the correct class label list with this model, and where can I find it?

Thanks!

**Comment by wasserth** [comment]
The correct label index list can be seen here: https://github.com/wasserth/TotalSegmentator#class-details
