### ISSUE TITLE
lung_vessels task - model details

### ISSUE THREAD

**Issue by kretes** [wasserth/TotalSegmentator#116]
Hello, 

first of all thanks for the effort on making such an awesome model & package!

I have a question about a subtask `lung_vessels` - how was the model trained for this task?

In readme you write `lung_vessels: lung_vessels (cite [paper](https://www.sciencedirect.com/science/article/pii/S0720048X22001097)), lung_trachea_bronchia`
but - 
1. the cited paper for lung vessels describes a non-trainable approach to vessel segmentation, and it comes with its own implementation at https://github.com/fsc-mib/travel. I understand what you provide in TotalSegmentator is a model trained somehow on dataset acquired using cited approach? 
2. no reference model for `lung_trachea_bronchia` 

thanks!

**Comment by wasserth** [comment]
We used the approach described in the paper to create lung vessels and bronchia segmentations on the totalsegmentator dataset. Then we manually checked where those segmentations worked well (it did not work well for all cases). Then we trained a nnunet on those cases (rougly 250 cases). This is the lung_vessels model.

**Comment by kretes** [comment]
Thanks very much for the clarification!

**Comment by lordmoinak1** [comment]
Thank you for sharing this model. Have you made the ~250 cases with segmented lung vessels publicly available? If not, do you plan to release them in the future?
