### ISSUE TITLE
issues regarding skeletal muscle

### ISSUE THREAD

**Issue by loneblues** [wasserth/TotalSegmentator#117]
It appears that the coastal cartilages are segmented as skeletal muscle. 
Is there a way around?

**Comment by wasserth** [comment]
At the moment there is no easy solution for that.

**Comment by wasserth** [comment]
I am currently working on adding segmentations of coastal cartilages.

**Comment by loneblues** [comment]
Sorry for the late response. Great news regarding coastal cartilages! Will be happy to test when it arrives!

**Comment by wasserth** [comment]
Coastal cartilages are now part of totalsegmentator.
