### ISSUE TITLE
Error when using python 3.7 on windows

### ISSUE THREAD

**Issue by Arputikos** [wasserth/TotalSegmentator#120]
I've installed python 3.7 with simpleitk 2.0.2 and torch, and I cannot even import totalsegmentator:
`from totalsegmentator.python_api import totalsegmentator`
because I get an error: 
`urllib3 v2.0 only supports OpenSSL 1.1.1+, currently "
ImportError: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with OpenSSL 1.1.0h  27 Mar 2018. See: https://github.com/urllib3/urllib3/issues/2168`

Change minimum python version requirement please

**Comment by wasserth** [comment]
This seems to be related to the following issue: https://github.com/wasserth/TotalSegmentator/issues/119

Try to manually install urllib3 with a fixed version (e.g.  1.26.15).

**Comment by wasserth** [comment]
I pushed a fix to the master branch. Can you check if it works for you know?
