### ISSUE TITLE
Retraining the model

### ISSUE THREAD

**Issue by aaekay** [wasserth/TotalSegmentator#124]
I am trying to retrain the model, in order to do that, the dataset you provided must be in the format of nnu net. Is there any script you can provide for the same conversion?

**Comment by wasserth** [comment]
There is no such script available. You will have to write your own.

**Comment by aaekay** [comment]
ohkay thanks

**Comment by ibro45** [comment]
I've created this repo for preprocessing the data:
https://github.com/AIM-Harvard/TotalSegmentator-to-nnUNet-format-convert

**Comment by wasserth** [comment]
Great! Thanks for providing this.
