### ISSUE TITLE
missing Xvfb on newer Macs

### ISSUE THREAD

**Issue by dieserobin** [wasserth/TotalSegmentator#126]
When trying to create preview files on a MacBook (OSX 13.2.1 running a jupyter notebook with python 3.10) I got an error telling me that Xvfb could not be found. The solution is quite simple. Apple stopped shipping Xvfb a while ago, but you can simply download it at [xquartz.org](www.xquartz.org) – then running this command in the notebook worked for me:

`os.environ["PATH"] += os.pathsep + '/opt/X11/bin'`

Theses instructions are a short version of [getting xvfb to work in jupyter notebook on m1 mac](https://stackoverflow.com/questions/71933644/getting-xvfb-to-work-in-jupyter-notebook-on-m1-mac)
(thank you for creating TotalSegmentator!)

**Comment by wasserth** [comment]
Thanks for pointing this out.
