### ISSUE TITLE
possible nifti header issue 

### ISSUE THREAD

**Issue by deepakri201** [wasserth/TotalSegmentator#13]
Hi, 

I've been able to successfully use your tool to create segmentation nii.gz files. However, I have noticed potential issues in the preservation of the nifti header information, and the ability to load the files in various programs. 

For instance, here is the nifti header from the original CT file that I pass to the network: 
![image](https://user-images.githubusercontent.com/59979551/187548591-484c4cb4-507b-4698-b8ef-963367e450b8.png)

And here is the resulting one from the segmentation: 
![image](https://user-images.githubusercontent.com/59979551/187548638-9d716346-4a35-47f7-83b4-99bab9326148.png)

It seems like there are some differences in the pixel spacing. 

I also noticed that the resulting labels are unable to be opened in all viewers. For instance in 3DSlicer, the resulting error occurs.  
![08_30_22_slicer_error_opening_total_segmentator](https://user-images.githubusercontent.com/59979551/187576944-dc8d94fd-9cea-484a-ad96-59de99d0b1b6.JPG)

Here is a [dropbox link](https://www.dropbox.com/s/o3zsebg27nxscg0/TotalSegmentator_nifti_header_issue.zip?dl=0) to the input CT nifti file and a resulting label nifti file. 

Thank you!

**Comment by wasserth** [comment]
Thanks for pointing this out. The spacing of the output image can be slightly different, but you can basically round that to the same spacing as the input. I will add a fix in the future to do this automatically.
The 3DSlicer error is actually a well known ITK error for loading nifti images which unfortunately happens for newer ITK versions and ITK did not yet fix this. This is not a  TotalSegmentator issue.

**Comment by fedorov** [comment]
Whether it is a Total Segmentator issue or not, it appears to be impossible to view the results of Total Segmentator using most commonly used tools (ITK and Slicer).

Which tools do you recommend for visualizing the results of Total Segmentator?

**Comment by wasserth** [comment]
I made some adaptations which might reduce this problem. When you install TotalSegmentator from the latest master branch does the problem still occur?
```
pip install --upgrade git+https://github.com/wasserth/TotalSegmentator.git
```

**Comment by deepakri201** [comment]
Thank you for the fixes! The pixel spacing issue is still present, but I was able to load the nii.gz files in 3DSlicer successfully. :)

**Comment by wasserth** [comment]
I did another fix. Now the output spacing should be identical to the input spacing.

**Comment by pieper** [comment]
thanks for the fixes @wasserth 👍 

Just wanted to report that the latest Slicer preview versions (5.1 post [this update to ITK](https://github.com/Slicer/Slicer/commit/3389dd83ed7af0e1366d310ba852b27e8ea62c9a) appear to have fully resolved this issue so older totalsegmentator files load correctly now.  I think you could close this issue.

**Comment by wasserth** [comment]
Great. Thank you for this update.
