### ISSUE TITLE
High resolution version not working

### ISSUE THREAD

**Issue by rajanish4** [wasserth/TotalSegmentator#130]
Hi,

I just want to inform that I have been using a public dataset for abdominal ct. I found that for the 3 datasets, the segmentator doesnt work in high resolution, but it works in fast mode (although not as good prediction as one would expect for high res anyway). What could be the reason behind this anomaly?

**Comment by wasserth** [comment]
What is the error message you get?

**Comment by rajanish4** [comment]
There is no error message, i am able to get segmentation maps, however many of them are either empty or of very bad quality. The dataset i use is this one: https://www.frontiersin.org/articles/10.3389/fphys.2021.732711/full#B3
I know that the soft tissue range in ct is [-200, 400], but i have found that in this range, this dataset shows very whitish image without much contrast. I believe the data distribution somehow doesnt correspond to soft tissue range for this dataset and hence i believe maybe one of the reason why segmentator does not work as well.

**Comment by wasserth** [comment]
The HU values have to be the original HU values. If the value range of the HU values was changed (like it seems the case for this image), then totalsegmentator does not work anymore.
