### ISSUE TITLE
TotalSegmentator could not install packages due to an OSError

### ISSUE THREAD

**Issue by katherineli1** [wasserth/TotalSegmentator#134]
I've tried installing TotalSegmentator on a Predator laptop running Windows 11 a couple times now but I keep running into the error "ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: " with a long path name looking for a file entitled "experiment_planner_2DUNet_v21_RGB_scaleto_0_1.py"

Prior to the error it said "Installing collected packages: argparse, nnunet-customized, fury, TotalSEgmentator"

I have Python 3.11.3 and Pytorch 2.0.1+u117

**Comment by wasserth** [comment]
Unfortunately I have not come across this error message before.

**Comment by katherineli1** [comment]
The issue appears to specifically occur when installing nnunet-customized. Do you know if this package is something I can manually install? Or if there is an error with the package when using pip to install it?
