### ISSUE TITLE
Mapping of TotalSegmentator segment labels to SNOMED

### ISSUE THREAD

**Issue by fedorov** [wasserth/TotalSegmentator#135]
In our project, we store the results of totalsegmentator as a DICOM Segmentation object, and to do that properly we are mapping individual labels into appropriate terms from [SNOMED](https://browser.ihtsdotools.org/). In the process of doing that we ran into the questions related to mapping "authochton" label, see discussion here: https://github.com/vkt1414/Cloud-Resources-Workflows/commit/83739e8a7cc66a42a3cf3af2aaa36a6ae3a73c35#r116804198.

Can you please comment/confirm if ["Erector spinae"](http://dailybuild.ihtsdotools.org/?perspective=full&conceptId1=44947003&edition=MAIN&release=&languages=en) is the appropriate term? If not, can you provide further clarification about the definition of "authochton" to help with our mapping?

As a related note, would you consider including and maintaining the mapping as part of this repository? This mapping was initially created by @lassoan in https://github.com/lassoan/SlicerTotalSegmentator/blob/main/TotalSegmentator/TotalSegmentator.py#L317. We identified some issues with that original mapping, and are currently refining it here https://github.com/vkt1414/Cloud-Resources-Workflows/blob/main/configs/TotalSegmentator/TotalSegmentator%20v1%20SCT%20mapping%20-%20total.csv, with the plan to update the mapping in SlicerTotalSegmentator when done. Arguably, maintaining this mapping centrally in the totalsegmentator repository would make most sense.

cc: @vkt1414 @dclunie

**Comment by wasserth** [comment]
The autochton corresponds mostly to erector spinae, but not completely. Unfortunately there is not one fixed anatomical structure if perfectly fits to. So we can either go with erector spinae or do not assign a snomed term.

In general I agree that maintaining this mapping in the totalsegmentator repo would make the most sense. However, I am not an expert in snomed labels. If you provide a table I am happy to put it into the repository and upon new input I am also happy to update the table. But I will not be able to keep it up to date based on my own knowledge.

**Comment by wasserth** [comment]
We tried to segment the "intrinsic back muscles". In German that is called autochtone back muscles. Our radiologist defined that. Not sure if snomed has a label for that. It is probably a combination of several smaller muscles.

**Comment by vkt1414** [comment]
@wasserth Thanks for your help with this. @fedorov I found this reference calling intrinsic muscles as deep muscles of the back, and SNOMED does have a reference. https://teachmeanatomy.info/back/muscles/intrinsic/                  
 Link to SNOMED: https://termbrowser.nhs.uk/?perspective=full&conceptId1=244849004&edition=uk-edition&release=v20230412&server=https://termbrowser.nhs.uk/sct-browser-api/snomed&langRefset=999001261000000100,999000691000001104

**Comment by wasserth** [comment]
I think deep muscles of the back could be a good fit.

**Comment by dclunie** [comment]
Yes, I can live with [244849004](https://snomed.info/id/244849004) - seems like a good choice if you want to include transversospinales as well as erector spinae.

**Comment by vkt1414** [comment]
> Yes, I can live with [244849004](https://snomed.info/id/244849004) - seems like a good choice if you want to include transversospinales as well as erector spinae.

Thank you, Dr. David. I'll go ahead and update.

**Comment by fedorov** [comment]
Excellent, great to see this resolved so efficiently!

>  If you provide a table I am happy to put it into the repository and upon new input I am also happy to update the table. But I will not be able to keep it up to date based on my own knowledge.

@wasserth can you please suggest the preferred format and location for that mapping file? We can commit what we have, and we can try to maintain it as you introduce new terms in the future.

**Comment by wasserth** [comment]
I added the mapping here:
https://github.com/wasserth/TotalSegmentator/blob/master/resources/totalsegmentator_snomed_mapping.csv

It is a exact copy for your csv file.

Feel free to submit changes to this file when needed.

**Comment by fedorov** [comment]
Thank you, I consider this resolved.

@wasserth going forward, I would have a strong preference that these contributions are managed via pull requests, so that there is recognition of the contribution of the individuals and projects who helped by putting that mapping together.

**Comment by wasserth** [comment]
I thought just creating the file is the smallest amount of work for all. But I understand that this will not show the contributors clearly and this might be important for some people. I can remove the content of the file and you can create a PR for it. Then things will be clearer. Shall we do it this way?

**Comment by fedorov** [comment]
Jacob, I definitely don't want to create any extra work for you! In fact, one of the reasons I proposed to make a PR was to have you do even less work. Let's just leave it the way it is for now.

**Comment by fedorov** [comment]
v2 labels added in https://github.com/wasserth/TotalSegmentator/pull/218.
