### ISSUE TITLE
Task_id not found or KeyError for "--roi_subset

### ISSUE THREAD

**Issue by ryanayf** [wasserth/TotalSegmentator#136]
I am using the option `--roi_subset` to obtain individual segmentation masks on `clavicle`, `scapula `etc, by calling their class names as follows: 

**When running using shell script:**
` --roi_subset clavicula_left clavicula_right scapula_left scapula_right
`
The error: 
![image](https://github.com/wasserth/TotalSegmentator/assets/61911315/e006931f-477b-4827-81fd-f98d738fecd7)

**When debugging in Python:** 
It stops at  \totalsegmentator\nnunet.py", line 65, in _get_full_task_name
``` 
Exception has occurred: ValueError
task_id 517 not found
```

Would you have any insights to this error or am I using `--roi_subset` correctly? Thank you very much. 
TotalSegmentator version: 1.5.5

**Comment by wasserth** [comment]
I think this bug is fixed in 1.5.6. Can you try again with the new version?

**Comment by ryanayf** [comment]
Yes `--roi_subset` works with 1.5.6. Great thanks! :)
