### ISSUE TITLE
the verison of nnunet in your work

### ISSUE THREAD

**Issue by qingwang-usc** [wasserth/TotalSegmentator#137]
Dear  Authors:
         Thank you for contibuting the excellent work! And I want to konw the version of nnunet of your work. Is it v1 or v2? Looking forward to your reply. Thank you very much!

**Comment by wasserth** [comment]
we are using v1 at the moment. I am currently working on upgrading to v2.

**Comment by qingwang-usc** [comment]
ok, thank you for your reply!
