### ISSUE TITLE
Unable to run with CPU when a Cuda GPU of any sort is connected

### ISSUE THREAD

**Issue by Jebsta** [wasserth/TotalSegmentator#139]
# The Problem

Running the project with `--fast` parameter the program will still use a GPU if found.

Because the GPU only has 3GB of VRAM the program stops with a CUDA out of Memory Error.

Therefore the program can't be run on this machine.

# Background

We have a PC with powerfull CPU and much RAM at our disposal with a small GPU for some small tasks and graphics. 

# Question

Is there an option to force CPU use? (I know it is slow)

**Comment by wasserth** [comment]
TotalSegmentator v2 now supports a flat `device`
