### ISSUE TITLE
1--roi_subset and 2 nii.gz

### ISSUE THREAD

**Issue by angolin22** [wasserth/TotalSegmentator#141]
Thanks for your work, which helps me a lot. Here, I want to ask some question:
1 when I use the '--roi_subset vertebrae_L5 vertebrae_L4 vertebrae_L3 vertebrae_L2 vertebrae_L1', the output segmentation file is empty, so I don't get the segmentation file. Please ask the usage of '--roi_subet'. In addition, if I want to get the **skeleton** segmentation file, how can I do?

2 I want to get the output segmentation file like 'segmentation.nii.gz', may I ask how to set it up

**Comment by wasserth** [comment]
Thanks for your feedback. I will have to investigate why roi_subset does not work as intended. 
There is no segmentation of "skeleton".
If you want to get one segmentation file instead of multiple you can use the argument "--multilabel".

**Comment by angolin22** [comment]
thanks for your reply, for 2: I would like to obtain segmentation in the. nii.gz format instead of the .nii format. May I ask how to set it up?

**Comment by wasserth** [comment]
If you do `TotalSegmentator -i my_image.nii.gz -o my_segmentation.nii.gz --multilabel` you should get .nii.gz
Also without --multilabel you should get .nii.gz

If this does not work, which command are you using?

**Comment by angolin22** [comment]
thanks for your reply! this command works!

**Comment by angolin22** [comment]
In addtion, I would like to ask that can the sternum be segmented, as shown in the area marked in red in the picture below? 
![image](https://github.com/wasserth/TotalSegmentator/assets/19361669/aea9fd65-ceac-4df5-aa3d-9fb7a4bf3810)

**Comment by wasserth** [comment]
I am currently working on v2 of TotalSegmentator and it will contain a Sternum segmentation.

**Comment by angolin22** [comment]
Wow, that's great!  Cloud I ask when the v2 of TotalSegmentator will be released?

**Comment by MMdeB** [comment]
I have also a problem using the roi_subset. I am using the Python API and if I run the code
`totalsegmentator(input_path, output_path, ml=True, fast=True, roi_subset=['kidney_right' 'kidney_left'])`
I will get a segmentation file with all segmentations in it, not only the kidneys. Am I doing something wrong?
Thanks in advance

**Comment by wasserth** [comment]
The segmentations are done in 5 parts. If you select roi_subset you will get one of the 5 parts, which also contains some other masks than the ones which you specificed in roi_subset. So this is intended.

**Comment by ryanayf** [comment]
Thank you once again for the great framework. 
I am using TotalSegmentator from python_api, and would like to segment the whole vertebrae (C1...T1...L1...L5) into one segmentation file (.nii.gz). I tried with multilabel option ml='True' and it contains some other masks too. 

May I ask if there is similar option in python_api like combine_masks for `vertebrae` as in command line ? 
eg. 
`totalseg_combine_masks -i totalsegmentator_output_dir -o combined_mask.nii.gz -m lung
`

Thanks a lot :)

**Comment by wasserth** [comment]
As you correctly suggested you can use `totalseg_combine_masks` for that. However, this is only available on the command line. But you could easily copy the code of this script and run it in python yourself.
