### ISSUE TITLE
pip not installing files as executables

### ISSUE THREAD

**Issue by MattAWard** [wasserth/TotalSegmentator#142]
totalseg_ and TotalSegmentator are appearing as generic files rather than executables in Python311/Scripts after install via pip. As such, TotalSegmentator is not recognised as a command when executed from the command line (Python311/Scripts is in PATH). Any idea what's going on here?

![pip_install_files](https://github.com/wasserth/TotalSegmentator/assets/119061663/61cfe3b7-eb9c-4871-9416-2bfcb43c3a89)

**Comment by wasserth** [comment]
I am not a windows user, therefore I do not really know the windows details around this.
One user reported that it worked by creating a batch file and inside calling TotalSegmentator:

Basically, one needs to make a batch file (a txt file with extension .bat).

The batch file contains the following line

call C:\ProgramData\Anaconda3\Scripts\activate MySegTool

C:\Users\YourUserName\.conda\envs\MySegTool\python C:\Users\YourUserName\.conda\envs\MySegTool\Scripts\TotalSegmentator -i %1 -o %2 --fast --body_seg --ml

call deactivate


C:\ProgramData\Anaconda3\Scripts\activate -> replace this folder by the directory where the activate function is found. MySegTool is the environment that you have created and where the totalsegmentator was installed. I created the environment with anaconda and installed TotalSegmentator with pip in that environment. This line is executed to activate the needed environment.

C:\Users\YourUserName\.conda\envs\MySegTool\python -> replace by directory where the python.exe in your local environment can be found. 

C:\Users\YourUserName\.conda\envs\MySegTool\Scripts\ -> should be the directory where the TotalSegmentator script (=actually a python script, but without extension .py) can be found

%1 and %2 are the arguments that can be provided when running from command line...in my case input and output file name. I have preset some settings like --fast etc, but also these can be provided from arguments list when calling the batch file from command line.

How to use the script

open doswindow (cmd), then type:
RunTotalSegmentator inputfilename outputfilename

inputfilename is represented by %1 \, outputfilename is represented by %2 within the batch script. Input and outputfilenames with full pathname.

**Comment by MattAWard** [comment]
Thanks @wasserth much appreciated 👍
