### ISSUE TITLE
Model generalizability issue on low-dose chest CT images

### ISSUE THREAD

**Issue by allyn1982** [wasserth/TotalSegmentator#144]
Hi, I ran TotalSegmentator on low-dose chest CT images to segment several anatomical structures in the chest, however, the algorithm missed most vertebrae for a lot of cases. Can you help me debug this? Thank you.

<img width="1408" alt="Screenshot 2023-07-10 at 3 24 40 PM" src="https://github.com/wasserth/TotalSegmentator/assets/37195634/4e7b450b-037f-4b9b-bf38-9d7573185643">
<img width="1403" alt="Screenshot 2023-07-10 at 3 25 12 PM" src="https://github.com/wasserth/TotalSegmentator/assets/37195634/b5fd0a2c-5069-42a6-92a6-267df501d42b">

**Comment by wasserth** [comment]
Your images seem to have a different orientation than the typical CT image. The vertebrae should be on the right instead of the left if you look at the small image and the very left of the screenshot. You can try to flip your image along the x or y axis.

**Comment by allyn1982** [comment]
Flipping alongside the y-axis works. Thank you so much! 

![Capture](https://github.com/wasserth/TotalSegmentator/assets/37195634/546ced61-b3f6-4d3c-b050-e8fa100571de)
