### ISSUE TITLE
Is there a segmentation of the entire heart contour?

### ISSUE THREAD

**Issue by angolin22** [wasserth/TotalSegmentator#147]
Thanks for your work! May I ask that is there a segmentation of the entire heart contour, like this?
![image](https://github.com/wasserth/TotalSegmentator/assets/19361669/1f09cae9-77fb-485c-a4d4-e40e85670c7f)

**Comment by francescopisu** [comment]
Yes, it's called Heart.nii.gz

**Comment by wasserth** [comment]
I would recommend to use the command `totalseg_combine_masks -i totalsegmentator_output_dir -o combined_mask.nii.gz -m heart` (see https://github.com/wasserth/TotalSegmentator#other-commands) to combine the heart subparts to one heart segmentation.

**Comment by angolin22** [comment]
ok, does it need to predict the selfparts of the heart first?

**Comment by wasserth** [comment]
yes, you need to run the normal totalsegmentator command first

**Comment by angolin22** [comment]
thanks, the result is as follows:
![image](https://github.com/wasserth/TotalSegmentator/assets/19361669/199b1f79-f815-47b0-af09-ca94dd26f6a0)

But this result is not what I want, I want the contour of the whole heart
