### ISSUE TITLE
Fast mode with Python API

### ISSUE THREAD

**Issue by MattAWard** [wasserth/TotalSegmentator#148]
How do you run TS with fast mode via the Python API? I.e. is there an argument somewhere in

`from totalsegmentator.python_api import totalsegmentator`
`totalsegmentator(input_path, output_path)`

to add `args = fast` or something similar?

**Comment by wasserth** [comment]
Yes, you can use `fast=True`.

For all arguments see: https://github.com/wasserth/TotalSegmentator/blob/master/totalsegmentator/python_api.py
