### ISSUE TITLE
Failed to load nifti file

### ISSUE THREAD

**Issue by penyepesto** [wasserth/TotalSegmentator#152]
I am trying to import some NIFTI files from the total segmentator dataset in Slicer 5.2.2. But some files are not open and give an error like this:“[VTK] ReadData: This is not a nrrd file
[VTK] vtkMRMLStorageNode::ReadData: Failed to read node ct (vtkMRMLVectorVolumeNode1) from filename=‘C:/Totalsegmentator_dataset/s0000/ct.nii.gz’
[VTK] vtkMRMLVolumeArchetypeStorageNode::ReadDataInternal: Failed to instantiate a file reader
[VTK] vtkMRMLStorageNode::ReadData: Failed to read node ct (vtkMRMLVectorVolumeNode2) from filename=‘C:/Totalsegmentator_dataset/s0000/ct.nii.gz’
[VTK] vtkMRMLVolumeArchetypeStorageNode::ReadDataInternal: Cannot read file as a volume of type Volume [fullName = C:/Totalsegmentator_dataset/s0000/ct.nii.gz]: FileFormatError. Number of files listed in the node = 0. File reader says it was able to read 1 files. File reader used the archetype file name of C:/Totalsegmentator_dataset/s0000/ct.nii.gz [reader 0th file name = C:/Totalsegmentator_dataset/s0000/ct.nii.gz].
[VTK] vtkMRMLStorageNode::ReadData: Failed to read node ct (vtkMRMLScalarVolumeNode1) from filename=‘Totalsegmentator_dataset/s0000/ct.nii.gz’
[Qt] void __cdecl qSlicerIOManager::showLoadNodesResultDialog(bool,class vtkMRMLMessageCollection *) Errors occurred while loading nodes: “Error: Loading C:/Totalsegmentator_dataset/s0000/ct.nii.gz - load failed.\n”” I tried the volume, segmentation, and transform options, but they’re not helping. There are 1205 files in the total segmentator dataset, but I cannot open 131 of them. Thanks in advice

**Comment by wasserth** [comment]
Apparently Slicer tries to open the nifti files as nrrd files, which does not work. This seems like a Slicer problem and I would recommend to ask in the Slicer community.
