### ISSUE TITLE
"How do you want to open this file?"

### ISSUE THREAD

**Issue by hadign20** [wasserth/TotalSegmentator#153]
I have installed the tool using:

`pip install TotalSegmentator`

on Windows 10 with Anaconda.

When I try to run it on the "Totalsegmentator_dataset" using:

`TotalSegmentator -i ct.nii.gz -o segmentations`

A window opens asking: "How do you want to open this file?"

How can I fix this?

Thank you

**Comment by ebinks123** [comment]
I renamed the TotalSegmentator file as TotalSegmentator.py and ran the code as TotalSegmentator.py -i ct.nii.gz -o segmentations. This seems to have fixed the issue. There might be other easier solutions.
