### ISSUE TITLE
Which Datasets the TotalSegmentor are pretrained on? 

### ISSUE THREAD

**Issue by sean-xr** [wasserth/TotalSegmentator#154]
Dear Authors,

Thank you so much for such an incredible model, I measured it on the Decathlon Spleen datasets and the results are great. However, it's a little bit difficult for me to tell the data that I'm using is already pretrained or not. According to the paper, TotalSegmentor is "1368 CT images were randomly sampled
from the years 2012, 2016, and 2020 from the University Hospital Basel picture archiving and
communication system (PACS)". Does it mean that the TotalSegmentor is also pretrained on some public datasets as well? If yes, is it possible for me to find the list of those datasets?

Thank you so much for your reply.

Best regards

**Comment by wasserth** [comment]
The totalsegmentator training dataset (https://zenodo.org/record/6802614) does not contain cases from any other public dataset.

**Comment by sean-xr** [comment]
> The totalsegmentator training dataset (https://zenodo.org/record/6802614) does not contain cases from any other public dataset.

Thanks for the answer!
