### ISSUE TITLE
Adding more radiomics features

### ISSUE THREAD

**Issue by jakalssj3** [wasserth/TotalSegmentator#158]
I am interested in using the pyradiomics implementation in TotalSegmentator to extract the radiomics features of each class. Is there any way to extend the list of the produced features? Currently it seems to only return to types of the features: "shape" and "firstorder". But it seems there are many more implemented in the "pyradiomics" package, e.g. "glcm" "gldm" "glrlm" and so on. Is it possible to enable these extra features to be reported?

**Comment by wasserth** [comment]
You will have to adapt the code to enable/add these additional features. So far this is not implemented.

**Comment by wasserth** [comment]
from totalsegmentator.python_api import totalsegmentator
