### ISSUE TITLE
How to call TotalSegmentator as a Python module?

### ISSUE THREAD

**Issue by rbumm** [wasserth/TotalSegmentator#16]
This is rather a question, no issue: 

What is the recommended way to import and call TotalSegmenator as a Python module?

Thank you.

**Comment by wasserth** [comment]
I did not intend this usecase therefore it is not as convenient. But you can still do it. Should not be too difficult. I would recommend using the method `nnunet_predict_image()` and you can see here how to use it: https://github.com/wasserth/TotalSegmentator/blob/master/bin/TotalSegmentator
