### ISSUE TITLE
[Feature request] Segment the Thymus

### ISSUE THREAD

**Issue by LifeIsStrange** [wasserth/TotalSegmentator#160]
The thymus is the most important immune organ and is considerably underlooked and underfunded in clinical trials against diseases and for increasing longevity.
Adding support for it is very important.
Especially since it is known to shrink and have its composition deteriorate with ageing or toxin exposure https://en.m.wikipedia.org/wiki/Thymic_involution
As a reminder it is necessary for lymphocyte T cells production, including T helpers and natural killer cells and is the primary cause of age related (adaptative) immunodeficiency and therefore e.g. of Covid mortality.
Note that some people have their thymus removed, which is known as a thymectomy
@wasserth friendly ping

**Comment by wasserth** [comment]
Thanks for pointing to the thymus. I have put it on the list for future releases.
