### ISSUE TITLE
error

### ISSUE THREAD

**Issue by yuanpengpeng** [wasserth/TotalSegmentator#164]
Why after I pip install TotalSegmentator, I run TotalSegmentator -i G:\part1\phd\Segmentation\case0_T00.nii.gz -o segmentations prompt 'TotalSegmentator' is not an internal or external command, nor is it an operable program
Or batch file, if this command is run, do I need to pull down the project and then run it in the project?

**Comment by Brian-Taylor8** [comment]
I assume this is on Windows, I ran into the same error and I solved it by specifying where the TotalSegmentator script is in like appdata/local/programs/python/pythonXX/Scripts, so total command was `python [path to TotalSegmentator script] -i etc`. However now I am getting an issue where it says it can't find the converted_dcm.json file, does anyone know how to solve that?

**Comment by yuanpengpeng** [comment]
> 

Yes, I am running on windows and encountered this problem, but there is no problem on linux, I hope relevant people can answer

**Comment by wasserth** [comment]
This error is now fixed in TotalSegmentator v2
