### ISSUE TITLE
Do you have the model architecture anywhere?

### ISSUE THREAD

**Issue by ZanChaudhry** [wasserth/TotalSegmentator#165]
Hello! Thank you for making such a great segmentation toolkit. I was interested in using the pre-trained weights of the organ segmentation pipeline for a transfer learning problem; however, for this I would need the model architecture, not just the weights. The pre-trained weights are in a .MODEL file, which seems to contain a state_dict with the weights, as well as some other information related to model training, but not the architecture itself. Is the model architecture somewhere in this repository?

**Comment by wasserth** [comment]
The model is normal nnunet model. You can check the nnunet code + documentation (https://github.com/MIC-DKFZ/nnUNet) for some more information. I would have to search for the model architecture myself.
