### ISSUE TITLE
Does TotalSegmentator rely on metadata from DICOM images/NIFTI images?

### ISSUE THREAD

**Issue by Brian-Taylor8** [wasserth/TotalSegmentator#166]
Thinking about applying this to a use case where DICOM images would be converted into a format for some software, and then "converted back" for use with this model. But DICOM/NIFTI images possess metadata about orientation of image and other such stuff, that may be difficult to track due to all the conversions. So, do you know what metadata matters to the TotalSegmentator model?

Edit1: Testing suggests that perhaps most headers aren't relevant, but the NIfTI affine, representing orientation/position of the image with respect to some reference, is important.

**Comment by wasserth** [comment]
Your assumption is correct: The nifti affine matrix is needed. Everything else does not matter.

**Comment by Brian-Taylor8** [comment]
Thanks!
