### ISSUE TITLE
Problems about Organ Segmentation Overlapping

### ISSUE THREAD

**Issue by JackRuihang** [wasserth/TotalSegmentator#168]
Hi,
First of all, thank you for making this amazing dataset publicly available! I am currently working on automatic multi-organ segmentation at EPFL CVLab. We train our model based on your dataset. However, we have noticed several instances where organ segmentations overlap with each other.
For example,
1) In s0046, heart_atrium_right and inferior_vena_cava are overlapped as following:
![image](https://github.com/wasserth/TotalSegmentator/assets/69423274/ca23cb1f-0afc-4231-ab52-fae6af1490c0)
The red organ is heart_atrium_right and the green one is inferior_vena_cava. When creating the segmentation mask, we consider that it is necessary to keep the integrity of the heart_atrium_right. Therefore, we manually assign the overlapping portion to the red section and remove it from the segmentation of the inferior_vena_cava. However, this manual handling of overlapping situations is complicated and time-consuming. Do you have any suggestions for dealing with such cases? Is there a more efficient way to handle overlapping organs and create accurate segmentation masks?
2) About the segmentation noise
Regarding segmentation noise, we have noticed some label inaccuracies in the dataset. In s0011, vertebrae_T5 and vertebrae_T6 are overlapped as following:
![image](https://github.com/wasserth/TotalSegmentator/assets/69423274/9bc4d296-0876-4300-8311-b86172fe23cf)
However, these two vertebrae should have minimal cross-sectional overlap physiologically (although I'm not entirely certain about this). This suggests inaccuracies in the segmentations in the dataset.
Furthermore, in s01342, aorta and iliac_artery_left are overlapped as following:
![image](https://github.com/wasserth/TotalSegmentator/assets/69423274/57578889-48ba-4685-9c42-3d10291aeb7d)
The aorta is outlined with a red circle. We have noticed that this organ occupies very few voxels in the 3D image. Moreover, there are numerous other organ segmentations that contain only a few voxels in the images. Consequently, it is challenging to determine whether these are label inaccuracies introduced during the training process with nn-Unet, or if they represent true organ segmentations.
Do you have any insights into these two situations? Are both of these issues a result of labeling inaccuracies during the training process with nn-Unet?

Thank you in advance for your response.

Best,
Ruihang Jiang

**Comment by wasserth** [comment]
Hi, 
thanks for your questions. There is indeed some overlap and some inaccuracies. However, since this is rather minor accross the entire dataset the resulting model is still working very well.
We use the following code to combine the masks. We just add one by one and the later one overwrite the earlier one in case of overlapping:
https://github.com/wasserth/TotalSegmentator/blob/master/totalsegmentator/libs.py#L214

**Comment by JackRuihang** [comment]
Get it! Thank you for the reply.
