### ISSUE TITLE
Passing Multiple .nii Files

### ISSUE THREAD

**Issue by idinsmore1** [wasserth/TotalSegmentator#171]
This is not an issue, more of a future feature request if possible. nnUNet's documentation recommends passing multiple files/arrays/etc. to the inference model if possible instead of one file/array at a time, as it rapidly speeds up total inference time. Looking through the code, it does not seem that Total Segmentator has this option available. If this could be implemented in a future release as an option that would be amazing for our workflow. Thanks for such an amazing tool!

**Comment by wasserth** [comment]
Building such a feature would be quite complicated unfortunately since everything is build around one input and one ouput file. Therefore, such a features will not happen in the near future :(

**Comment by idinsmore1** [comment]
No problem! Thanks for the quick response!
