### ISSUE TITLE
The order of tissue_types seems wrong

### ISSUE THREAD

**Issue by czw90130** [wasserth/TotalSegmentator#173]
the order of tissue_types in line 293 map_to_binary.py was:
1: "subcutaneous_fat"
2: "skeletal_muscle"
3: "torso_fat"

Seems it should be:
1: "subcutaneous_fat"
2: "torso_fat"
3: "skeletal_muscle"

**Comment by wasserth** [comment]
This is correct. Thanks for pointing to this bug! I fixed it.
