### ISSUE TITLE
totalseg_import_weights -i will set to wrong dir

### ISSUE THREAD

**Issue by czw90130** [wasserth/TotalSegmentator#174]
totalseg_import_weights -i will import weights to:
 ~/.totalsegmentator/nnunet/results/nnUNet/3d_fullres
But the loading path is:
 ~/.totalsegmentator/nnunet/results

**Comment by wasserth** [comment]
Thanks for pointing this out. It is indeed a bug. But actually totalseg_import_weights is no longer needed in totalsegmentator v2 for the default usage.
