### ISSUE TITLE
Unjustified resampling in radiomics feature extraction?

### ISSUE THREAD

**Issue by fedorov** [wasserth/TotalSegmentator#176]
It appears that the image is resampled to 3x3x3 prior to the extraction of the radiomics features:

https://github.com/wasserth/TotalSegmentator/blob/master/totalsegmentator/statistics.py#L29

I do not see why this would be needed. I think resampling to a uniform matrix is important while extracting texture features, but here only shape and firstorder are extracted.

**Comment by wasserth** [comment]
This 3x3x3 resampling is only done if you use the `--fast` option. This greatly increases runtime and the resulting volume. Otherwise the original resolution is used.
