### ISSUE TITLE
problems with skin segmentation

### ISSUE THREAD

**Issue by paccinimartina** [wasserth/TotalSegmentator#178]
I tried to use the task for skin segmentation with the line:

TotalSegmentator -i ct.nii.gz -o seg -ta body

but it doesn't work. In gives me the following error: 

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Martina\\.totalsegmentator\\nnunet\\results\\nnUNet\\3d_fullres\\Task273_Body_extrem_1259subj\\nnUNetTrainerV2__nnUNetPlansv2.1\\plans.pkl'
Exception ignored in: <totalsegmentator.libs.DummyFile object at 0x000002308DDE8110>
AttributeError: 'DummyFile' object has no attribute 'flush'

However, if I do not specify the body task, the segmentation works but it does not present the skin segmentation, that is actually the only thing I need.
Is there something I can do to fix it?

**Comment by wasserth** [comment]
Which version of totalsegmentator are you using?

**Comment by paccinimartina** [comment]
It is version 1.5.6

**Comment by wasserth** [comment]
Can you try again with the newest totalsegmentator?
```
pip install --upgrade totalsegmentator
```

**Comment by paccinimartina** [comment]
Now it worked, thank you!

**Comment by arobinson1331** [comment]
Hello, I am using the same command only getting segmentations of body trunk and body extremities, but no skin. Is there a way to pull out just the skin segmentation? I have tried --roi_subset skin and -ta body --roi_subset skin, but get the errors seen in the images. 
![MicrosoftTeams-image (34)](https://github.com/wasserth/TotalSegmentator/assets/82711435/47df1d52-14c5-498e-a88c-deeea23b2459)
![MicrosoftTeams-image (35)](https://github.com/wasserth/TotalSegmentator/assets/82711435/c81987ce-67a3-4d19-bd26-e00dd628659b)

**Comment by wasserth** [comment]
just use `-ta body` without setting `roi_subset`.

**Comment by wasserth** [comment]
the skin segmentation does not work with `--ml`. Can you try without?
