### ISSUE TITLE
V2 Install not working

### ISSUE THREAD

**Issue by bradfeiger** [wasserth/TotalSegmentator#181]
Probably a really simple solution, but I'm getting the following errors when running `pip install TotalSegmentator`:
`ERROR: Could not find a version that satisfies the requirement nnunetv2==2.2 (from TotalSegmentator) (from versions: 2.0)
ERROR: No matching distribution found for nnunetv2==2.2 (from TotalSegmentator)
`

Any easy fix?

**Comment by wasserth** [comment]
Strange. I have never experienced this error. This should normally work.

**Comment by bradfeiger** [comment]
Upgraded to Python 3.9 from 3.8 and it worked fine.

**Comment by wasserth** [comment]
Good point. I updated the readme to contain this information.
