### ISSUE TITLE
`pip install tts...`  in the `colab`, it warns: 'restart runtime'...what's wrong? 

### ISSUE THREAD

**Issue by jumbojing** [wasserth/TotalSegmentator#184]
As shown in 👇 the figure:

![image](https://github.com/eltzanis/multi-structure-CT-dosimetry/assets/10215735/12ac926b-3b98-4820-a49d-41d5359d62cf)

restart As 👆🏻 the prompt and '!pip install TotalSegmentator' again:

![image](https://github.com/eltzanis/multi-structure-CT-dosimetry/assets/10215735/3bef736d-23b4-44f9-b848-0119cccdd9c3)

**Comment by wasserth** [comment]
This is actually a error of the version of the `requests` package. This can happen on python < 3.10. Can you try with a colab with python >= 3.10 ?
