### ISSUE TITLE
V2 seems quite slower than V1 with --fast option?

### ISSUE THREAD

**Issue by hilalshaath** [wasserth/TotalSegmentator#185]
Thanks for this amazing work, I ran an experiment, but saw perf desegregation with the new version with the fast option.   

HW: RTX 3090
In the older version, running this:
TotalSegmentator --fast -i ./train_images/19/14374/ -o ./19/14374/ -rs spleen kidney_left kidney_right liver esophagus colon duodenum small_bowel stomach

Takes 24 seconds

With the newer version running the command:

TotalSegmentator --fast -i dicomfolder -o outputfolder -rs spleen kidney_left kidney_right liver esophagus colon duodenum small_bowel stomach

Takes 60 seconds

dicom image shape (512, 512, 673)

I think I might be missing the right config to see perf improvement

**Comment by hilalshaath** [comment]
it seems that it samples way too much than V1, I tried with both GPU and CPU, seems perf is quite slower. I don't know if this helps?

import torch
print(torch.__version__)
2.0.1+cu117

**Comment by wasserth** [comment]
When run the same commands I get 29s runtime for v1 and 25s runtime for v2. So I have a small improvement. The improvement is only small because of the fast option. If you run without fast the speed improvement you get with roi_subset will be a lot larger.
Are you using the identical input image for both comparisons?

**Comment by lassoan** [comment]
FYI, I've tested the segmentation time in 3D Slicer 5.4 on Windows with TS v1 and v2 and found that v2 is slightly slower. For me, the slightly longer computation time is justified, as v2 provides considerably more segments.

|                        | v1      | v2      |
|------------------------|---------|---------|
| CTChest / total        | 103 sec | 118 sec |
| CTChest / total / fast | 31 sec  | 40 sec  |
| CTLiver / total        | 128 sec | 139 sec |
| CTLiver / total / fast | 50 sec  | 53 sec  |
