### ISSUE TITLE
-ml does not output any files

### ISSUE THREAD

**Issue by GyulaMaloveczky** [wasserth/TotalSegmentator#186]
When I add -ml to the code it does not output any file to the output folder.

`!TotalSegmentator -f  \
-i /kaggle/temp/new227 \
-o /kaggle/temp/new2000  \
-rs spleen kidney_left kidney_right liver colon small_bowel stomach --nr_thr_saving 4`

**Comment by wasserth** [comment]
When you add `--ml` the `-o` argument does not take a directory path anymore but a the path to the output nifti file. Does it work then?

**Comment by GyulaMaloveczky** [comment]
Yes, it works, thank you very much!
