### ISSUE TITLE
Why is the `roi_subset` parameter not working?

### ISSUE THREAD

**Issue by jumbojing** [wasserth/TotalSegmentator#189]
![image](https://github.com/wasserth/TotalSegmentator/assets/10215735/035b5056-cf4c-411e-941c-2798222e973e)

but get a `total` result: 👇

![image](https://github.com/wasserth/TotalSegmentator/assets/10215735/041b8cb7-5f4c-4184-b2f3-49faec49d06a)

**Comment by wasserth** [comment]
If you pass more than 10 classes to roi_subset it will run the total model, because this does not really take any longer. But I see that there are valid cases where you want to specify more than 10 classes. I just pushed a update to the master branch which allows more than 10. You have to install totalsegmentator from the latest master branch to use it (see readme for how to do this).

**Comment by jumbojing** [comment]
But I had run two vertebrae before, the results were the same! @wasserth

**Comment by wasserth** [comment]
Hmmm, this is strange. If you call TotalSegmentator from the command line (instead of python api) do you have the same problem?

**Comment by jumbojing** [comment]
I updated the  `TotalSegmentator`, ran 2 vertebrae, and obtained 👇:

![image](https://github.com/wasserth/TotalSegmentator/assets/10215735/f6e7f6c1-fd32-4b0e-8ec5-052b119e11da)

**Comment by jumbojing** [comment]
and 👇:
![image](https://github.com/wasserth/TotalSegmentator/assets/10215735/5c475c43-3368-42e3-a419-05fadd3c1bd7)

**Comment by jumbojing** [comment]
I guess those  maybe related to labels (in `dataset`) confusion...

**Comment by jumbojing** [comment]
@wasserth Can we make a classification option for `total` tasks based on weight files, so that we can better `roi_sub`  segment them?

**Comment by jumbojing** [comment]
![image](https://github.com/wasserth/TotalSegmentator/assets/10215735/4ba624e5-2233-419d-ad12-ac7ba81a31df)
![image](https://github.com/wasserth/TotalSegmentator/assets/10215735/8b437341-40d5-4502-9439-a156cffecbfb)

@wasserth 

I tried changing [the 'total' task to '292'](https://github.com/jumbojing/TotalSegmentator/blob/c613ee52011aad2e21fb0699094410fb1b8eb1e9/totalsegmentator/python_api.py#L90), got a nice result 👆🏻 

But the spinal classification of 'roi_subset' is empty 👇

![image](https://github.com/wasserth/TotalSegmentator/assets/10215735/3c7da1c7-bb61-4503-b13f-2277688d4514)

**Comment by wasserth** [comment]
Can you try again with totalsegmentator version 2.0.2
Now you only should get the labels with you specified in roi_subset.

**Comment by jumbojing** [comment]
```
 TotalSegmentator -i ~/Documents/GitHub/SAMed/datasets/workDir/data/verse768_CT-ax.nii.gz -o vbSc.nii.gz -f -rs spinal_cord
```
![image](https://github.com/wasserth/TotalSegmentator/assets/10215735/657740f7-3a06-4206-8070-9541e6cdf9fe)

**Comment by wasserth** [comment]
This problem might be related to another bug which is just fixed. Can you try again with TotalSegmentator v2.0.5 ?
