### ISSUE TITLE
python_api failing on windows

### ISSUE THREAD

**Issue by Brian-Taylor8** [wasserth/TotalSegmentator#190]
The python api seems to also be broken on windows for me. I'm feeding it straight NIFTI files that work fine through the regular TotalSegmentator script. Like, TotalSegmentator -i inputNIfTI -o outputNIfTI is working swimmingly, but totalsegmentator(inputNIfTI, outputNIfTI) seems to result in what looks like a threading error? The readout is something along the lines of:
```
myPythonLocation\multiprocessing\spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Exception ignored in: <totalsegmentator.libs.DummyFile object at 0x00000212DEA35F70>
AttributeError: 'DummyFile' object has no attribute 'flush'
...
```
And it also reruns lines from earlier in my program and seems to loop forever. I've just been using `subprocess.run("TotalSegmentator -i inputFile -o outputFile` instead, but it would be nice to call the python api directly. Has anyone gotten the python api to work on windows? Maybe I'm missing something very basic.

**Comment by wasserth** [comment]
which version of totalsegmentator are you using?

**Comment by Brian-Taylor8** [comment]
I'm using v2(the one that got pushed to pip). I also couldn't get the python_api from v1 to work on windows(was using the prior v1 that was on pip right before v2 was pushed).

**Comment by wasserth** [comment]
For me the python api is working on windows. Therefore it is really difficult to tell what the problem might be.

**Comment by Brian-Taylor8** [comment]
Can I ask what version of windows, python, and pytorch you are using? I'm on windows 10, torch 2.0.1 + cu118, python 3.9.5. It seems this[ type of multiprocessing error](https://stackoverflow.com/questions/67328927/multiprocessing-throwing-runtime-error-after-executing-p-start) can crop up due to os changes, so would be good to know!
