### ISSUE TITLE
Some issues with public dataset v2

### ISSUE THREAD

**Issue by marcus-wirtz-snkeos** [wasserth/TotalSegmentator#193]
I was checking the new v2 TotalSegmentator public dataset (https://zenodo.org/record/8367088) and found contrast issues with the scans `s0184`, `s0224`, `s0830`, and `s0992` (exemplarily, left: old v1 dataset, right: new v2 dataset, sorry for the poor debugging image presentation):
![image](https://github.com/wasserth/TotalSegmentator/assets/24655255/e347cddd-98ef-4232-b0e6-8b50d4c545d3)

Furthermore, the image data in scans `s0045`, `s0248` seem to be completely empty.

Something also seems odd with the Hounsfield scale in scan `s0864`, range of (-9758 to 4349).

I downloaded the zip file with the MD5 hash `fd65f71cf3ef78c67a3740909ecef674`

Can you verify these issues?

**Comment by wasserth** [comment]
I get similar issues for s0184, s0224, s0830, s0864. I will check that.
s0045, s0248 are fine for me. 
My zip file hash is different. Can you send the precise link from which you downloaded it?

**Comment by marcus-wirtz-snkeos** [comment]
Sure, this is the link which I used for the zip file download: 
https://zenodo.org/records/8367088/files/Totalsegmentator_dataset_v2.zip?download=1

On the webpage it still shows me the same MD5 hash that I downloaded two weeks ago:
![image](https://github.com/wasserth/TotalSegmentator/assets/24655255/02f94bc2-ef3b-4969-a6a8-89ab437a098e)

**Comment by wasserth** [comment]
It took me some time to figure out the problem: My RAM had a small hardware error which resulted in randomly broken files, but only very rarly (roughly 1 in 1000 files got broken). Now I bought new RAM and it seems fine now. I uploaded a new version (2.0.1) of the dataset. This should hopefully fix the problems.

**Comment by marcus-wirtz-snkeos** [comment]
Great, I'll let my sanity checks run again and let you know!

**Comment by marcus-wirtz-snkeos** [comment]
Sanity checks passed, thanks for the fix!
