### ISSUE TITLE
Could you please share your checkpoint file?

### ISSUE THREAD

**Issue by Fivethousand5k** [wasserth/TotalSegmentator#2]
Hi! Great work! I wonder if you can share your nnUNet checkpoint files. Thanks!

**Comment by wasserth** [comment]
Hi,
they are already uploaded to zenodo:
https://zenodo.org/record/6802342
https://zenodo.org/record/6802358
https://zenodo.org/record/6802360
https://zenodo.org/record/6802366
https://zenodo.org/record/6802452
https://zenodo.org/record/6802052

**Comment by Fivethousand5k** [comment]
OK! Thanks!
