### ISSUE TITLE
volume statistics incorrect

### ISSUE THREAD

**Issue by huanghoujing** [wasserth/TotalSegmentator#204]
Hi, thanks for the great tool.

When I try it for skull segmentation, the output `skull.nii.gz` looks good, but the `statistics.json` shows empty volume.

`skull.nii.gz`:
![image](https://github.com/wasserth/TotalSegmentator/assets/13362456/90dae45a-3326-4a23-bcc3-8830ce16fca5)

`statistics.json`:
```json
    "brain": {
        "volume": 1271018.1383047104,
        "intensity": 39.9
    },
    "skull": {
        "volume": 0.0,
        "intensity": 0.0
    },
...
```

The input DICOM sample is:
[HN-CHUM-004.zip](https://github.com/wasserth/TotalSegmentator/files/13063773/HN-CHUM-004.zip)

Thank you for looking into this question.

**Comment by wasserth** [comment]
Whenever the segmentation mask touches the image border, the volume will be set to 0 because obviously the mask is incomplete. If you want to change this behaviour you can use the parameter `--stats_include_incomplete`.

**Comment by huanghoujing** [comment]
Thank you for the clear explanation. I will try that.
