### ISSUE TITLE
medical research based on total segmentator

### ISSUE THREAD

**Issue by Girosella** [wasserth/TotalSegmentator#205]
hi, I am currently used this tool to do several studies in medical imaging. I went smoothly with version1, after newly published version, I got problems when downloading the new models. just wanna find out the reason  and if others got the same problem.
still grateful for your great work.

**Comment by wasserth** [comment]
Do you get any error message? Which specific version are you using? (run `TotalSegmentator --version`) What operating system are you using?

**Comment by Girosella** [comment]
wow, your reply is so fast and surprising. Thanks in advance.
I tried TS(short for total segmentator) v1 previously for part of data and now new data came and I am trying to continue using the orginal model. During the trial, I encountered several problems: 1 virtual environment I used previously can't work properly. it stuck in downloading models,sometimes in downloading,sometimes in unzip,said it's not a proper zip file. 2 I tried to upgrade TS to the newest version, I encountered problem mainly as the cuda version too old, and if I didn't use GPU, the downloading part still stuck me. I tried to downloaded model manually,and put it under the directory, but the code did't recognize this manually downloaded file(a zip file and I extracted and put it under /nnunet/results/nnUNet/3d_fullres/weights,not working).
Now I am trying to upgrade my cuda version to see if I can successfully run the model.
Thanks for your timely reply, really surprised me.

**Comment by Girosella** [comment]
When I am trying to install most recently published version with command: pip install git+https://github.com/wasserth/TotalSegmentator.git
 an error occur once more which lead to my failure. please show me the correct way. Thanks.
![WeChatWorkScreenshot_81ed7b55-6fc4-40f3-960c-3b5994bd0545](https://github.com/wasserth/TotalSegmentator/assets/50125794/c033cfd1-c5ba-43f7-b083-64259d12ff61)

**Comment by Girosella** [comment]
and besides, when I am trying yo install simpleitk==2.0.2, I find it's not supported in python >3.9 since you can see from the picture below. my python version is 3.10. 
![WeChatWorkScreenshot_c296d305-b5cd-4ca1-928c-f2d1d33e2664](https://github.com/wasserth/TotalSegmentator/assets/50125794/05046b8d-c9ca-4c25-9480-2fe514636e70)

**Comment by wasserth** [comment]
I would recommend to create a completely new virtual environment with python 3.9 and then try again in the new environment. It also seems that the download often fail for you. Is your internet connection slow or unreliable?

**Comment by Girosella** [comment]
> I would recommend to create a completely new virtual environment with python 3.9 and then try again in the new environment. It also seems that the download often fail for you. Is your internet connection slow or unreliable?
as for my connection, I can download the dataset directly fromthe github,but with code, it failed. 
I tried  the docker way yesterday and one package conflicts with totalsegmentator named batchgenerators, I'd try and make it reinstalled. but wonder the docker should be working when I pulled as my workmate did for totalsegmentator v2.
