### ISSUE TITLE
Retraining coronary_arteries model

### ISSUE THREAD

**Issue by vikashg** [wasserth/TotalSegmentator#210]
Hello @wasserth, 
I want to retrain the coronary arteries model from TotalSegmentator. As you said that the `coronary_arteries` model is trained on a small dataset. I want to train it on a larger dataset. As you mentioned in the README that we should follow the nnUNet guide to retrain/finetun the models. But I don't think that the coronary arteries are part of the nnUNet model sets. In this case I was wondering if you can suggest what is the appropriate way to train the coronary arteries model. 

Thank 
Vikash

**Comment by wasserth** [comment]
You need your own dataset for coronary arteries. Then you train a default nnU-Net following the default nnU-Net documentation.

**Comment by vikashg** [comment]
Ok Thanks I will try this. However, I was under the impression that nnUnet or Total Segmentator are a combination of multiple models for different resolutions and body parts. So, I wanted to fine-tune the already available coronary artery model instead of training something from scratch. I was wondering if there is a mechanism to choose the appropriate model.

**Comment by denbonte** [comment]
Sorry to jump in randomly, @wasserth!

@vikashg, to the best of my knowledge, TotalSegmentator uses a `3d_fullres` architecture from nnU-Net (no k-fold cross-validation or multiple models plus the ensembling). You would need to fine-tune only the [coronary-artery model](https://github.com/wasserth/TotalSegmentator/blob/master/totalsegmentator/libs.py#L263) that I think is available upon request (free academic license per the README file).

The current TotalSegmentaror (TotalSegmentatorV2) is [built on top of nnU-NetV2](https://github.com/wasserth/TotalSegmentator/blob/master/setup.py#L34), so [fine-tuning should be pretty straight forward](https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/pretraining_and_finetuning.md#using-pretrained-weights).

I should disclaim that I haven't tried this myself, but I got here after discussing with a former colleague about [this paper](https://www.frontiersin.org/articles/10.3389/fnimg.2023.1252261/full) that just came out on Frontiers and used nnU-NetV2 3T-to-7T fine-tuning for brain MRI segmentation. I was doing a bit of reading on the topic this morning, and going down a bit of a rabbit hole led me here. I hope this can help somehow, and it would be helpful if you report back your findings 😄

**Comment by vikashg** [comment]
Thanks @denbonte  I will report back to you soon 

Vikash

**Comment by nairouzshehata** [comment]
I wanted to fine-tune the aorta model too because it seems to segment fine except the aortic root and I have part of my aorta dataset segmented including aortic root so wanted to fine tune TotalSegmentator aorta model using my dataset. Please let me know if you were able to do so an
d how. Thanks!
