### ISSUE TITLE
Required Python version

### ISSUE THREAD

**Issue by Renal-Of-Loon** [wasserth/TotalSegmentator#219]
Heya,

So I stumbled on this by accident.
Currently, the project requires nnunetv2==2.1, which in turns requires python 3.9.

If you try to install totalsegmentator with python <3.9 you get a slightly odd error of not being able to find nnunetv2==2.1 (which I _do_ understand why now that I see the python version issue).

I would then suggest that the minimum python version for totalsegmentator be bumped to 3.9 to just avoid possible issues and have a clear outline of the issue.

Cheers!

**Comment by wasserth** [comment]
Good point. Thanks for pointing to this. I updated the setup.py file to include python>=3.9 as requirement.
