### ISSUE TITLE
Problem of args in totalsegmentator/libs.py

### ISSUE THREAD

**Issue by YukiOkita** [wasserth/TotalSegmentator#22]
Dear TotalSegmentator developers,

Hello, I found a problem in the following lines. ([part1](https://github.com/wasserth/TotalSegmentator/blob/d20513ddac4b18a53de6280acc484eb89cfc3250/totalsegmentator/libs.py#L273), [part2](https://github.com/wasserth/TotalSegmentator/blob/d20513ddac4b18a53de6280acc484eb89cfc3250/totalsegmentator/libs.py#L281)). It seems that `args` isn't defined in any line.

**Comment by wasserth** [comment]
Thanks for pointing out this bug. I just pushed a fix.

**Comment by YukiOkita** [comment]
Thank you very much!
