### ISSUE TITLE
Segmentations getting arbitrary cutoffs

### ISSUE THREAD

**Issue by EvelKylenievel** [wasserth/TotalSegmentator#220]
Hello, I am using TotalSeg 2.0.5 and getting consistent issues with flat edges for some pieces of anatomy.  My aortas and some of my lungs are getting a clean cut as if a much too small bounding box gets placed on the CT image before segmentation begins.  As you can see in the 3rd of the images I am uploading, the CT image contains the full anatomy but it fails to segment correctly.  

I am running it as follows:
TotalSegmentator -i input -o output --roi_subset lung_lower_lobe_left lung_lower_lobe_right
TotalSegmentator -i input -o output -ta heartchambers_highres

Thank you for your help!

-Lung Segmentation with flat face (not a great lung seg in general)-
![gray_lung_cutoff](https://github.com/wasserth/TotalSegmentator/assets/55407988/b69f617b-6176-43bc-8561-6b64f93913a9)

-Aorta seg standalone-
![aorta](https://github.com/wasserth/TotalSegmentator/assets/55407988/ba4adb40-c2ff-490a-9218-062944789853)

-Aorta seg with source CT-
![aorta_and_ct](https://github.com/wasserth/TotalSegmentator/assets/55407988/8fe954a5-040b-4e32-a7c0-6f63818d03c8)

**Comment by StefanFischer** [comment]
Same issue here :)
Thank you for the nice work on the totalsegmentator, it is a great tool!

**Comment by StefanFischer** [comment]
Actually this issue does not occur in totalsegmentator v1 for the same CT input volumes

**Comment by wasserth** [comment]
When you use the option `--roi_subset` or a subtask (`-ta`) which focuses on one body region, then a fast low resolution model is run first to crop the image to the region of interest and then the actual model is run. Probably this fast low resolution model failed. Does it work well without `--roi_subset`? Can you share the dataset which me so I can try to reproduce it and maybe find out why the fast low resolution model fails?

**Comment by StefanFischer** [comment]
![grafik](https://github.com/wasserth/TotalSegmentator/assets/24388946/70a14a1e-546c-4c31-84fd-776c27b5a2f9)
this is the segmentation failure of the aorta. the segmentation was run with "-ta total".
i send you the regarding volume via email.
failure of the aorta is in our dataset at around 80%

**Comment by wasserth** [comment]
I figured out the problem with the data from Stefan: He was running first `-ta total` and then `-ta heartchambers_highres`. `heartchambers_highres` will crop to only the heart region and also segment the aorta. This highres cropped aorta segmentation then overwrites the file with the same name from `-ta total` if you chose the same output folder.
The reason why the lung segmentation is also cropped is not really clear to me.

**Comment by EvelKylenievel** [comment]
Thank you for the help Jakob! And for maintaining this great tool.  I am getting around this issue by running --roi_subset aorta after heartchambers_highres. The lung segmentation issue persists but it's not nearly as important for now.
