### ISSUE TITLE
Capability of pectoralis muscle segmentation

### ISSUE THREAD

**Issue by loneblues** [wasserth/TotalSegmentator#224]
For body composition analysis and other various purposes, pectoralis (major and minor) muscle segementation is recieving much attention. 
Also it would be nice if intrathoracic and abdominal torso fat can be separated. 
Can this be achieved by totalsegmentator?

**Comment by wasserth** [comment]
Thanks for these feature requests. I will put them on my list.
Along which anatomical boundary would you like to separate intrathoracic and abdominal torso fat?

**Comment by loneblues** [comment]
Hi! 
I wasn't aware of your reply! I might have missed them in my mailing list. 
As far as I know, the intrathroacic and abdominal fat is usually separated by the diaphragm. 
The diaphragm segmentation is also very challenging, but would be useful if it becomes available! 
Thanks!
