### ISSUE TITLE
Download and use local weigths

### ISSUE THREAD

**Issue by jbousso** [wasserth/TotalSegmentator#226]
Hello! 

I am opening this issue because I have a problem with the download of the weights. I am actually using the 1.5.7 version of the total segmentator, and this error appears : 
![image](https://github.com/wasserth/TotalSegmentator/assets/150698494/af8bcf3e-b03f-49bb-9980-ccbceac4a72c)

To overcome this problem, I've seen that I have to download the weights locally, and I don't know exactly how I am supposed to do ? And once I have download them, how can I use the total segmentator and specify him to use the local weights instead of download them from the web ? 

Thanks for your answer!

**Comment by wasserth** [comment]
This is strange. In version 1.5.7 there should be no URL pointing to zenodo anymore. All should point to github releases. Are you maybe still running a earlier version?

**Comment by jbousso** [comment]
No I am on the 1.5.7 version for sure. If it's preferable I can update my version but I still don't know how I can download and use weights locally?

**Comment by wasserth** [comment]
You can use the following command to download the weights in an extra command:

```
totalseg_download_weights -t total
```

**Comment by egrossiord** [comment]
I would like to re-open this issue as I have the same kind of question! I was able to download the weights for version 1.5.7 of the Total Segmentator with the command given in your reply @wasserth so already thanks for that. How can I use the downloaded weights to run the total segmentator ?
