### ISSUE TITLE
Lung Segmentation only

### ISSUE THREAD

**Issue by rgutsche-siemens** [wasserth/TotalSegmentator#228]
How can lung segmentation be exclusively performed? Currently, there is no explicit option to specify this task.

**Comment by wasserth** [comment]
To exclusively perform lung segmentation using TotalSegmentator, you can utilize the `--roi_subset` option along with the names of the classes corresponding to lung structures. Here's how you can do it:

1. If you are running TotalSegmentator from the command line, you can specify the lung-related classes directly using the `--roi_subset` option. For example:

```bash
TotalSegmentator -i input.nii.gz -o output_folder --roi_subset lung_upper_lobe_left lung_upper_lobe_right lung_lower_lobe_left lung_lower_lobe_right lung_middle_lobe_right
```

This command will instruct TotalSegmentator to segment only the listed lung structures and ignore other classes.

2. If you are using the Python API, you can pass the list of lung-related classes to the `roi_subset` argument:

```python
from totalsegmentator.python_api import totalsegmentator

totalsegmentator(input_path, output_path, roi_subset=['lung_upper_lobe_left', 'lung_upper_lobe_right', 'lung_lower_lobe_left', 'lung_lower_lobe_right', 'lung_middle_lobe_right'])
```

Note that you need to know the exact class names as defined in the TotalSegmentator model. Check the documentation or the `map_to_binary.py` file in the TotalSegmentator repository for the correct class names.
