### ISSUE TITLE
Cannot obtain good results for NLST dataset

### ISSUE THREAD

**Issue by annareithmeir** [wasserth/TotalSegmentator#229]
Hi,

I am segmenting the openly available NLST lung CT dataset obtained from https://cloud.imi.uni-luebeck.de/s/pERQBNyEFNLY8gR .
The resulting segmentations of the ribs and vertebrae do not look good, is this to be expected?
![Screenshot from 2023-11-15 15-46-33](https://github.com/wasserth/TotalSegmentator/assets/26904567/51b2bc4a-b68a-44d8-bb2e-3331c97fde89)

Thank you for your help!

**Comment by wasserth** [comment]
The images are not in standard orientation. The vertebrae should be at the lower end of the image. If you flip along the y-axis it works as expected.

**Comment by annareithmeir** [comment]
ah thanks a lot! it works now
