### ISSUE TITLE
Link in README.md leads to 403 Forbidden

### ISSUE THREAD

**Issue by nai62** [wasserth/TotalSegmentator#23]
Hi, thank you for sharing your great work.

I found that the link in README.md on the text of `Created by the department of [Research and Analysis at University Hospital Basel]`, which leads to the URL: https://www.unispital-basel.ch/ueber-uns/departemente/theragnostik/kliniken/radiologie-und-nuklearmedizin/lehre-und-forschung/forschung/team-forschungskoordination , results in 403 Forbidden. Could you confirm if it's the right URL?
FYI I accessed it from Japan.

**Comment by wasserth** [comment]
This is strange. I can open it from any device without errors. Can you access the main page? https://www.unispital-basel.ch/

**Comment by nai62** [comment]
Thank you for your prompt reply. Oops, the main page also leads me to 403 Forbidden. And I found I can successfully access both pages with my mobile phone with its WiFi turned off. Probably the pages prohibit access from some IP addresses including mine.
I sincerely apologize for bothering you. Let me close this issue.
