### ISSUE TITLE
Segmentation noise

### ISSUE THREAD

**Issue by lvonasek** [wasserth/TotalSegmentator#230]
Hello, I tried to overlap the segmentations over the original images but it contains noise:
![24](https://github.com/wasserth/TotalSegmentator/assets/6472545/c5d3d2c5-29e7-4065-afcd-8777f77acdc4)

Are there any plans to improve the ML model on this topic? In 3D the noise is not visible because it is inside of the organs.

The script+data I used: https://github.com/lvonasek/Dicom2ColoredOBJ

**Comment by wasserth** [comment]
Can you share the dataset where this happens so I can try to reproduce the issue?

**Comment by wasserth** [comment]
When running `TotalSegmentator -i demo_data -o seg` I get good segmentations without any holes. Is it maybe a problem with how you display the masks?

**Comment by lvonasek** [comment]
That is possible. I will take a deeper look into it over the weekend.

**Comment by lvonasek** [comment]
You were right, the problem was on my side (fixed by https://github.com/lvonasek/Dicom2ColoredOBJ/commit/5dd52a6a033951a59794c8e0892a23667bd14964).

Now the output looks like this:
![24](https://github.com/wasserth/TotalSegmentator/assets/6472545/0fe134eb-2621-44e4-9ede-54009f800c76)
