### ISSUE TITLE
Where are output files saved?

### ISSUE THREAD

**Issue by PlutoniumMind** [wasserth/TotalSegmentator#232]
Where are the output files saved? I ran the tool on both my own dataset and example4d.nii.gz, and I cannot find any generated output. 

Note: I had to reinstall pytorch to be compatable with CUDA 11.8 as the GPU was not detected (or CUDA) before. 
`pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118`

(TotalSegmentator) C:|█████████>TotalSegmentator -i "C:|█████████\TotalSegmentator\Lib\site-packages\nibabel\tests\data\example4d.nii.gz" -o segmentations--ml

If you use this tool please cite: https://pubs.rsna.org/doi/10.1148/ryai.230024

WARNING: Input image has 4 dimensions. Only using first three dimensions.
Resampling...
  Resampled in 0.19s
Predicting part 1 of 5 ...
Predicting part 2 of 5 ...
Predicting part 3 of 5 ...
Predicting part 4 of 5 ...
Predicting part 5 of 5 ...
  Predicted in 2849.49s
Resampling...
Saving segmentations...
100%|████████████████████████████████████████████████████████████████████████████████| 117/117 [00:02<00:00, 39.83it/s]
  Saved in 3.59s

**Comment by DrachmaDroysen** [comment]
After `-o` you need to list the `/File/Path/For/Your/Output_Directory`

**Comment by PlutoniumMind** [comment]
Well, now that you say that it seems pretty obvious, but in my defense the usage instructions did not state much. That fixed the issue, thank you very much.
