### ISSUE TITLE
pip install  error

### ISSUE THREAD

**Issue by Tsuchiya-Naoki** [wasserth/TotalSegmentator#233]
When trying to install TotalSegmentator using 
`pip install TotalSegmentator`
the following error occurs.

```
ERROR: Could not find a version that satisfies the requirement nnunetv2==2.2 (from TotalSegmentator==2.0.4) (from versions: 2.0)
ERROR: No matching distribution found for nnunetv2==2.2 (from TotalSegmentator==2.0.4)
```

However, the installation of the older version (pip install TotalSegmentator=="1.5.6") is successful. 

Please provide guidance on how to resolve this issue.

**Comment by wasserth** [comment]
This is strange for two reasons: nnunetv2 2.2 should be available and you should actually get TotalSegmentator 2.0.5. This is the latest version (not 2.0.4). Your system somehow does not seems to be up to date.

**Comment by Tsuchiya-Naoki** [comment]
By updating the python version (3.11.0) I was able to install successfully.
Thank you!
