### ISSUE TITLE
'NoneType' object has no attribute 'build_network_architecture'

### ISSUE THREAD

**Issue by rgutsche-siemens** [wasserth/TotalSegmentator#234]
I get the following errror: 'NoneType' object has no attribute 'build_network_architecture'

Something happens during the prediction. Any idea?

This is my command line:

2023-11-21 16:41:47,332 - PleuraVizUtil.logger_util - INFO - Start lung segmentation: Total Segmentator

If you use this tool please cite: https://pubs.rsna.org/doi/10.1148/ryai.230024

Using 'fast' option: resampling to lower resolution (3mm)
Generating rough body segmentation...
Converting dicom to nifti...
  found image with shape (512, 512, 610)
Resampling...
  Resampled in 6.01s
Predicting...
2023-11-21 16:42:27,253 - PleuraVizUtil.logger_util - ERROR - Exception during execution of totalsegmentator function. Exception: 'NoneType' object has no attribute 'build_network_architecture'

**Comment by rgutsche-siemens** [comment]
``
    try:
        logger.info('Start lung segmentation: Total Segmentator')

        roi_subset = ['lung_upper_lobe_left', 'lung_upper_lobe_right', 'lung_lower_lobe_left', 'lung_lower_lobe_right',
                      'lung_middle_lobe_right']
        result = totalsegmentator(args.inputdir, tempOutData, output_type='nifti', roi_subset=roi_subset, fast=True, device='cpu')
    except Exception as e:
        logger.error(f'Exception during execution of totalsegmentator function. Exception: {e}')
    logger.info('Finished lung segmentation!')
``

**Comment by rgutsche-siemens** [comment]
This is my python code: 

`    try:
        logger.info('Start lung segmentation: Total Segmentator')

        roi_subset = ['lung_upper_lobe_left', 'lung_upper_lobe_right', 'lung_lower_lobe_left', 'lung_lower_lobe_right',
                      'lung_middle_lobe_right']
        result = totalsegmentator(args.inputdir, tempOutData, output_type='nifti', roi_subset=roi_subset, fast=True, device='cpu')
    except Exception as e:
        logger.error(f'Exception during execution of totalsegmentator function. Exception: {e}')
    logger.info('Finished lung segmentation!')
`

**Comment by rgutsche-siemens** [comment]
try:
        logger.info('Start lung segmentation: Total Segmentator')
        roi_subset = ['lung_upper_lobe_left', 'lung_upper_lobe_right', 'lung_lower_lobe_left', 'lung_lower_lobe_right',
                      'lung_middle_lobe_right']
        result = totalsegmentator(args.inputdir, tempOutData, output_type='nifti', roi_subset=roi_subset, fast=True, device='cpu')
    except Exception as e:
        logger.error(f'Exception during execution of totalsegmentator function. Exception: {e}')
    logger.info('Finished lung segmentation!')

**Comment by wasserth** [comment]
I think the method `build_network_architecture` comes form nnU-Net. Have you installed nnUNet? Otherwise I am a bit clueless about this.

**Comment by rcorredorj** [comment]
Hi,

Did you guys find a solution to this? I just installed the last version to perform a segmentation with the new model for MR images and I'm getting the following : 

**(AI_Sandbox) PS C:\> TotalSegmentator -i "C:\temp\t1_vibe_dixon_tra_dinamico_W_Series0028.nii.gz" --device cpu --fast --statistics --ml --task total_mr -o "C:\temp\LIVER" --verbose > "C:\temp\LIVER\log.txt"**

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\tmp\miniconda3\envs\AI_Sandbox\Scripts\TotalSegmentator.exe\__main__.py", line 7, in <module>
  File "C:\tmp\miniconda3\envs\AI_Sandbox\Lib\site-packages\totalsegmentator\bin\TotalSegmentator.py", line 132, in main
    totalsegmentator(args.input, args.output, args.ml, args.nr_thr_resamp, args.nr_thr_saving,
  File "C:\tmp\miniconda3\envs\AI_Sandbox\Lib\site-packages\totalsegmentator\python_api.py", line 379, in totalsegmentator
    seg_img, ct_img, stats = nnUNet_predict_image(input, output, task_id, model=model, folds=folds,
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\tmp\miniconda3\envs\AI_Sandbox\Lib\site-packages\totalsegmentator\nnunet.py", line 471, in nnUNet_predict_image
    nnUNetv2_predict(tmp_dir, tmp_dir, task_id, model, folds, trainer, tta,
  File "C:\tmp\miniconda3\envs\AI_Sandbox\Lib\site-packages\totalsegmentator\nnunet.py", line 242, in nnUNetv2_predict
    predictor.initialize_from_trained_model_folder(
  File "**C:\tmp\miniconda3\envs\AI_Sandbox\Lib\site-packages\nnunetv2\inference\predict_from_raw_data.py**", line 101, in **initialize_from_trained_model_folder**
    network = trainer_class.build_network_architecture(plans_manager, dataset_json, configuration_manager,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
**AttributeError: 'NoneType' object has no attribute 'build_network_architecture'**

Thanks!

RaC
