### ISSUE TITLE
Why is there only one label for the `vertebral body model`? Can we divide it into different corresponding levels with different labels? 

### ISSUE THREAD

**Issue by jumbojing** [wasserth/TotalSegmentator#236]
Why is there only one label for the `vertebral body model`? Can we divide it into different corresponding levels with different labels? 

![image](https://github.com/wasserth/TotalSegmentator/assets/10215735/d2d8ec9a-a69a-4f81-b57c-7ee10e5c3963)

Just like the following 👇 (with 'total model'):

![image](https://github.com/wasserth/TotalSegmentator/assets/10215735/8d95d3e8-4875-4389-8d60-7a36daa8a138)

**Comment by wasserth** [comment]
The vertebrae_body mask is intended to be used to refine the individual vertebrae masks. Just take the intersection of both for each vertebrae. Then you have what you need.

**Comment by jumbojing** [comment]
@wasserth well...```vtArr01 * vbArr01 * lb```... 👌🏻
