### ISSUE TITLE
Some bad annotations in public v2 dataset

### ISSUE THREAD

**Issue by marcus-wirtz-snkeos** [wasserth/TotalSegmentator#245]
Hi there! I investigated a subset of about 100 samples of the v201 dataset (md5: fe250e5718e0a3b5df4c4ea9d58a62fe) and found some annotation issues with the following scans:

1. `s0092`: class `lung_upper_lobe_right` extends beyond the scan volume:
<img src="https://github.com/wasserth/TotalSegmentator/assets/24655255/3ec27986-ce54-4751-836b-51b6d8aceba8" width="250">

2. `s0201`: class `heart` is not in the right place
<img src="https://github.com/wasserth/TotalSegmentator/assets/24655255/4e5b5f3f-77cb-4440-91a8-5f93c7d67a85" width="250">

3. `s0513`: class `humerus_right` (green segment) is wrong here
<img src="https://github.com/wasserth/TotalSegmentator/assets/24655255/6656ae1a-541b-443c-b970-fb1fbc48f2eb" width="250">

4. `s0605`: class `lung_lower_lobe_left` extends lower than diaphragm
<img src="https://github.com/wasserth/TotalSegmentator/assets/24655255/ee5b1ea1-8c35-4bff-9c89-eee31206ca66" width="250">

I hope fixing these issues can help improving the next generation TotalSegmentator models. If not, feel free to just close this issue ;-)

Thanks for your good work!

Best,
Marcus

**Comment by wasserth** [comment]
Thanks for pointing these out. The labels of the dataset are not perfect and I am continuously fixing errors. So thanks for your contribution.

**Comment by wasserth** [comment]
I fixed the errors in the dataset. They will be part of our next release of the dataset (will take some time).
