### ISSUE TITLE
Number of classes in Python API

### ISSUE THREAD

**Issue by sean-xr** [wasserth/TotalSegmentator#247]
Dear Author,

Thanks for the great work! The TotalSegmentator is really useful and all the documentations are very well written:)

Since the version 2 has been released, may I ask when will the python API version be updated? When I'm using the Python API in my code for the segmentation, still I'm getting 104 output classes, so I guess I'm still using the old version.

Many thanks for the reply!

**Comment by wasserth** [comment]
When you install the newest pip package the python api will also use the new version. So I guess you still have the old totalsegmentator installted.
