### ISSUE TITLE
sslVerify error when running TS v2

### ISSUE THREAD

**Issue by MattAWard** [wasserth/TotalSegmentator#248]
An ssl certification error is causing Total Segmentator to crash during the running of the script. The error log suggests that the script is trying to communicate with host="objects.githubusercontent.com" which is blocked by the IT department at our hospital. Interestingly, this error did not appear when running v1, so I'm wondering if there's something in the new update that requires the script to speak to github upon each execution?

**Comment by wasserth** [comment]
v1 was downloading the weights from zenodo which was slow. v2 is now downloading the weights from github. Not sure why this is blocked by your hospital IT.

**Comment by MattAWard** [comment]
Thanks @wasserth. Could I ask why the weights are being redownloaded on each script execution? I'm no expert on the nnU-Net algorithm but I would have assumed that this information would be downloaded once during the installation, unless the weights are being tuned periodically?

**Comment by wasserth** [comment]
The weights are only downloaded once. But if your download failed, then it does not find any weights on the next run and tries to download them again.

**Comment by MattAWard** [comment]
Okay thanks so I suppose this must be some issue with my installation then, that it wasn't able to download the weights then so it is reattempting the download on the first execution of the script
