### ISSUE TITLE
The license model error 

### ISSUE THREAD

**Issue by Jerry7j** [wasserth/TotalSegmentator#251]
Dear TotalSegmentator community,

For the license model, I can only use this part: heartchambers_highres
![image](https://github.com/wasserth/TotalSegmentator/assets/51701056/0e2cccff-bf8e-4d8d-b588-edf4e025b5d2)

but the other four part: appendicular_bones, tissue_types, vertebrae_body, face give the subsequent error:
![image](https://github.com/wasserth/TotalSegmentator/assets/51701056/aa4edd31-5181-4198-996a-b065642cd521)
![image](https://github.com/wasserth/TotalSegmentator/assets/51701056/d617b39d-80e8-4d84-a6c9-2503871616bd)

Best,
Jerry

**Comment by wasserth** [comment]
It seems that the background worker died. Maybe it ran out of memory because your image is very big. Have you tried with a smaller image?
