### ISSUE TITLE
Hard pin on requests in PyPi release for python 3.10

### ISSUE THREAD

**Issue by marijncv** [wasserth/TotalSegmentator#252]
Currently, the release of TotalSegmentator has a hard pin on requests in the version available on PyPi (2.0.5). However, in the `setup.py`, there is some logic to only set this hard pin when installing with python 3.9. The current release is problematic for us using TotalSegmentator when we are trying to install with python3.10 but are hit with the hard pin on `requests` that is incompatible with our requirements universe.

Would it be possible to release separate wheels for the package for python versions 3.9 & 3.10, with 3.10 having no hard pin on requests?

Thank you in advance!

**Comment by wasserth** [comment]
The latest release (v2.0.5) should contain the logic in setup.py which uses a fixed `requests` only for python <= 3.9. So I do not really understand why your v2.0.5 does not contain this.

**Comment by marijncv** [comment]
The setup.py logic is only run when installing the source distribution. But there is also a built distribution available (see [here](https://pypi.org/project/TotalSegmentator/#files), and pip favors the built distribution over source distribution. When looking at the metadata for the built distribution, you can see the hard pin there:
```
wget https://files.pythonhosted.org/packages/e0/44/c99e5b42c7b567f66692cd0af3ae7cb5b8ddac9d7946853b1fa433a705a3/TotalSegmentator-2.0.5-py3-none-any.whl
unzip TotalSegmentator-2.0.5-py3-none-any.whl -d dist
cat dist/TotalSegmentator-2.0.5.dist-info/METADATA
```

My guess is that the built distribution was generated from a python3.9 process

**Comment by wasserth** [comment]
That is correct: I uploaded the pip packages from python 3.9.
Do you know how to create built distributions for each python version?

**Comment by marijncv** [comment]
After digging in some more it looks like there is no need for multiple built distributions, but we can instead make use of inline python constraints for the `install_requires` parameter as described [here](https://setuptools.pypa.io/en/latest/userguide/dependency_management.html#platform-specific-dependencies). See my [PR](https://github.com/wasserth/TotalSegmentator/pull/254) for a proposal!

**Comment by wasserth** [comment]
Great. Thanks for the PR. I just merged it.

**Comment by marijncv** [comment]
Thanks for the merge! Are you planning to release a new version to pypi soon?
