### ISSUE TITLE
Invalid(?) RTstructs generated

### ISSUE THREAD

**Issue by Renal-Of-Loon** [wasserth/TotalSegmentator#253]
Hello,

So I am not 100% certain if this belongs here or not, but I believe that it should at least be mentioned.

As it currently stands, Totalsegmentator can generate RTstructs (when using `dicom` as output), that seem to be invalid. In some cases a volume slice will only have 2 pixels of a volume/segmentation/organ, which translates to a 2 point polygon in the RTstruct, which is... not a valid polygon.

I am unsure if this should be an issue addressed by rt-utils or a post-process done by totalsegmentator, however. The issue has been brought up on the rt-utils package, here: https://github.com/qurit/rt-utils/issues/87

I imagine a "simple" postprocessing of checking if each slice has at least a count > 2 of an ROI would resolve the issue; but I am unsure of a nice fast way of doing this.

**Comment by wasserth** [comment]
Thanks for mentioning this. TotalSegmentator depends on rt-utils for generating RTstructs. It does not make sense to implement my own logic around that. So I have to wait for them to fix this problem.
