### ISSUE TITLE
Model weights for TotalSeg v1

### ISSUE THREAD

**Issue by ryanayf** [wasserth/TotalSegmentator#258]
Hi, I was using the TotalSegmentator **v1.5.6** for my previous code using python_api. Accidentally, I installed in the same Conda environment the TotalSegmentator **v.2.0.5.** as want to try out the new 'task'. (And v1.5.6 was uninstalled).

Now I try to reinstall back **v1.5.6** in the Conda env as my previous code depends on it, but have the following error: 

```
Downloading pretrained weights for Task 251 (~230MB) ...
Traceback (most recent call last): 
c:\users\Anaconda3\envs\manta2\lib\site-packages\requests\models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: http://94.16.105.223/static/Task251_TotalSegmentator_part1_organs_1139subj.zip
```
Would it please advice would the weights be still available and how shall I let the v1.5.6 to load it again?

Thanks a lot for the great work and new versions :)

**Comment by wasserth** [comment]
If you want to use totalsegmentator v1 you should use v1.5.7. Does it work when you try installing
`pip install --upgrade totalsegmentator==1.5.7`

Does it work after deleting `~/.totalsegmentator`? This will deleted all weights already downloaded. Then they are automatically redownloaded.
