### ISSUE TITLE
Where to find v2 addtional classes segmentation labels?

### ISSUE THREAD

**Issue by JixiangChen-Jimmy** [wasserth/TotalSegmentator#264]
Thanks for the awesome work! I notice that there are new classes added in v2, among which I am intereset in the patella, fibula and tibia parts. But after downloading the v2 dataset from https://zenodo.org/records/10047292, I can not find these classes in the segmentation folder. Did I use the wrong version, could you kindly provide some instructions?

**Comment by wasserth** [comment]
The training data for these classes is not public. See this document for more details: https://github.com/wasserth/TotalSegmentator/blob/master/resources/improvements_in_v2.md

**Comment by JixiangChen-Jimmy** [comment]
Thanks for the reminder, so it means the v2 training dataset support more classes, but the segmentation data regarding the newly added classes (not the new subjects) is not released?

**Comment by JixiangChen-Jimmy** [comment]
Thanks for the prompt reply!
