### ISSUE TITLE
Question about body outline annotation

### ISSUE THREAD

**Issue by GeorgBell** [wasserth/TotalSegmentator#270]
Dear authors,

thank you for the impressive and really useful work that you carried out and made it publicly available!
I am carrying out research where it is required to define the patient body surface as one of the pre-processing stages. We would like to retrain the model for body outline segmentation (body: body, body_trunc, body_extremities, skin). However, as far as I understood, the annotation for these classes is not available. With this regard, are you planning to make it publicly available (maybe under specific license or as a collaboration) at some point?

Thanks and best regards,
George

**Comment by wasserth** [comment]
Thanks for your interest in these tasks. So far we do not plan to make these public. You could use the model to generate these segmentations for the totalsegmentator dataset. The result should be pretty good.

**Comment by GeorgBell** [comment]
Thank you for the reply! I'll follow the recommendations.

**Comment by GeorgBell** [comment]
Thank you for the reply! I'll follow the recommendations.
