### ISSUE TITLE
ONNX Export

### ISSUE THREAD

**Issue by enochilluminant** [wasserth/TotalSegmentator#271]
Is there currently a way to export the final trained model into ONNX or some similar format? This would be to deploy the model in a standalone c++ or dotnet application. I can provide more information if needed!

**Comment by wasserth** [comment]
If nnU-Net suppports ONNX, then TotalSegmentator can also do this, because TotalSegmentator is using a nnU-Net model. As far as I know this is not supported by nnU-Net so far (https://github.com/MIC-DKFZ/nnUNet).

**Comment by shifuxiao** [comment]
I also recently trained my own model with nnunet, and I want to deploy this model into production, have you implemented it yet? Can we communicate?
