### ISSUE TITLE
Best image preprocessing methods?

### ISSUE THREAD

**Issue by grinerD** [wasserth/TotalSegmentator#276]
Just a question, are there some image preprocessing (preprocessing on the input CT image volume) procedures that improve performance?  For CT volumes with different acquisition parameters from the training set is it best to try and match (e.g. slice thickness)?  Does anyone have experience/tips on this subject?

**Comment by wasserth** [comment]
The model was trained with a wide range of images (e.g. different acquisition parameters), therefore it works equally well for most images. No specific preprocessing is needed, as long as you do not have a very unique and rare CT acquisition setting.
