### ISSUE TITLE
Adjusting the threshold to decrease the false postive

### ISSUE THREAD

**Issue by Yanhong0131** [wasserth/TotalSegmentator#277]
I am using the Total Segmentator while it seem have some false postive results. Could I adjust the threshold of the softmax results to get less false postive results?

**Comment by wasserth** [comment]
Theoretically you could do that, but this will result in missing a lot true positives. The default threshold of 0.5 typically works best and adjusting it does not help in most cases. Therefore TotalSegmentator does not contain an option to adjust the threshold.
