### ISSUE TITLE
libGL error: failed to load driver: swrast

### ISSUE THREAD

**Issue by sixitingting** [wasserth/TotalSegmentator#278]
When I used the --preview parameter, I encountered the following error:

Generating preview...
```
libGL error: MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: swrast
Aborted (core dumped)
```
Could you please tell me how to solve this? Thanks so much

**Comment by wasserth** [comment]
The error message you encountered indicates that there is a problem with your system's OpenGL installation. Specifically, it seems that the software rendering library `swrast` is either missing or cannot be found.

Here are some steps to potentially solve this issue:

1. **Install or Reinstall Mesa:**
   Mesa is an open-source software implementation of OpenGL, Vulkan, and other graphics API specifications. It provides the `swrast` driver, which is the software rasterizer for Mesa. To install or reinstall mesa, run the following command:

   ```bash
   sudo apt-get install --reinstall libgl1-mesa-glx libgl1-mesa-dri
   ```

2. **Update Your System:**
   Make sure your system's package lists and installed packages are up to date:

   ```bash
   sudo apt-get update
   sudo apt-get upgrade
   ```

3. **Set LIBGL_ALWAYS_SOFTWARE:**
   As a workaround, you can force the system to use software rendering by setting the `LIBGL_ALWAYS_SOFTWARE` environment variable to `1`. However, this may result in poor graphics performance. To set the variable, run this in your terminal before starting your application:

   ```bash
   export LIBGL_ALWAYS_SOFTWARE=1
   ```

4. **Check the Correct Paths:**
   The system is trying to load the `swrast_dri.so` file from certain paths but can't find it. Ensure that the file actually exists in one of the listed directories (`/usr/lib/dri/`, `/usr/lib/x86_64-linux-gnu/dri/`). If it's in a different location, you might need to create a symbolic link or update your library paths.

5. **Use xvfb-run (X Virtual Framebuffer):**
   If you are running an application that requires a GUI in a non-interactive session (like an ssh session or a script), you can sometimes work around graphics driver issues with `xvfb-run`, which allows you to run the application in a virtual framebuffer:

   ```bash
   xvfb-run --auto-servernum --server-args='-screen 0 1024x768x24' <your_command>
   ```

Replace `<your_command>` with the TotalSegmentator command you are using.

6. **Docker or Container Environments:**
   If you are running inside a Docker container or any other containerized environment, make sure the container's graphics stack is properly set up to allow software rendering.

At the end of the day, if you are not experienced with such issues or if the application is not critical for your work, you might want to seek help from someone with system administration or DevOps experience, as graphics driver issues can be particularly tricky to diagnose and resolve.

**Comment by forresti** [comment]
I have the same problem. I'm on an AWS server with L40S GPU and NVIDIA driver 570.

```
$ simulate
MuJoCo version 3.3.1
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
ERROR: could not create window

```
