### ISSUE TITLE
Data id mapping between v1 and v2

### ISSUE THREAD

**Issue by duducheng** [wasserth/TotalSegmentator#280]
Hi @wasserth , 

Thanks for the excellent work!

I would like to know whether there is an id mapping between v1 and v2. For instance, is s0000 in v1 and v2 the same? It seems at least their meta data are different.

I would also like to know the train-val split, is the v1 split compatible as v2?

Thanks in advance ;)

Jiancheng

**Comment by wasserth** [comment]
Between v1 and v2 the instances should be identical. v2 contains more meta data and the age might have changed slightly because we add noise to it for better anonymisation.
The train-test split is also compatible. The v2 test set contains all the test subjects from v1 plus a few new ones.

**Comment by duducheng** [comment]
Thank you! I will check this. 

Plus, it looks that the CT image sizes in the v1 and v2 are also different. Is there some special changes?
