### ISSUE TITLE
About DICOM Image Input

### ISSUE THREAD

**Issue by U-ma-s** [wasserth/TotalSegmentator#282]
Thanks for the excellent work!

Beginner's question:
I am trying to do a liver segmentation by inputting a CT image in DICOM format. Is it possible to input a file with a `'.dcm'` extension?
Or is there a way to convert the '.dcm' files to the format in the `'reference_files/example_ct_dicom'` folder?

**Comment by wasserth** [comment]
The input needs to be a complete 3d volume. A single .dcm file is only a single 2D slice. Therefore you need a folder with all the slices. This folder needs to be the input to TotalSegmentator.
