### ISSUE TITLE
Error trying to set the device to GPU in Jupyter notebook

### ISSUE THREAD

**Issue by Saumya-Gupta-26** [wasserth/TotalSegmentator#286]
Hi! I checked the function arguments of `totalsegmentator()` [here](https://github.com/wasserth/TotalSegmentator/blob/master/totalsegmentator/python_api.py). I know the default is to use GPU, but I still wanted to set it manually since the run time was a bit slow. Furthermore, I could not see any GPU usage via `nvidia-smi`. On trying to set the `device` argument, however, I get the below error. I am running the code from Jupyter Lab. Could there be any reason for this? 

![image](https://github.com/wasserth/TotalSegmentator/assets/16615692/ceaec1d5-a0a3-44de-bad5-76d9b395fda6)

**Comment by wasserth** [comment]
Which totalsegmentator version are you using? Can you update to the newest version?

**Comment by wsonia** [comment]
> Which totalsegmentator version are you using? Can you update to the newest version?

The version installed is 1.5.7 using "pip install TotalSegmentator"

**Comment by wsonia** [comment]
> > Which totalsegmentator version are you using? Can you update to the newest version?
> 
> The version installed is 1.5.7 using "pip install TotalSegmentator"

I transferred to the newest version, how to specify gpu?
<img width="1228" alt="image" src="https://github.com/wasserth/TotalSegmentator/assets/88081482/3db8a909-825f-4330-a47b-9cffd953e23b">

**Comment by wasserth** [comment]
Using gpu:1 is only possible in the newest master. In the latest pip version only `--device gpu` is possible.
