### ISSUE TITLE
requirements nnunet<2.3

### ISSUE THREAD

**Issue by ayalalazaro** [wasserth/TotalSegmentator#288]
Hi!
When installing Totalsegmentator in a fresh virtual environment via pip, it installs nnunetv2 v2.3. When running totalsegmentator I get an error stating that the downloaded weights do not fit the network architecture. I fixed it downgrading to nnunetv2 <2.3.
pip install --upgrade "nnunetv2 <2.3".  I think the requirements file should reflect this issue.

**Comment by wasserth** [comment]
For me it works for nnunetv2==2.3.1. There are problems with nnunetv2==2.3. Can you try with 2.3.1? If this does not work: Which totalsegmentator version are you using and how does the TotalSegmentator command look like you are running?

**Comment by ayalalazaro** [comment]
You are right, it works, it just happens that I got a warning with version 2.3.1: 
"/totalseg2/lib/python3.10/site-packages/nnunetv2/utilities/plans_handling/plans_handler.py:37: UserWarning: Detected old nnU-Net plans format. Attempting to reconstruct network architecture parameters. If this fails, rerun nnUNetv2_plan_experiment for your dataset. If you use a custom architecture, please downgrade nnU-Net to the version you implemented this or update your implementation + plans.
  warnings.warn("Detected old nnU-Net plans format. Attempting to reconstruct network architecture ""
and I confused it with another error that I fixed later (running totalsegmentator with python api in a script without a __main__ block.
Version 2.2.1 does not throw any warning.
Thanks for your quick reply!

**Comment by ayalalazaro** [comment]
By the way, I am calling totalsegmentator as follows:
`from totalsegmentator.python_api import totalsegmentator`

`totalsegmentator('rtdir', 'rtoutput', output_type="dicom", body_seg=True, verbose=True)`
