### ISSUE TITLE
pre-downloaded weights

### ISSUE THREAD

**Issue by mingtian126** [wasserth/TotalSegmentator#289]
Hello,
I download the current version, however due to the network connection, I have to download the v2.0.0-weights to make it running. It output masks but all zeros. Here's some warning: 
UserWarning:Detected old nnU-Net plans format. Attempting to reconstruct network architecture parameters. If this fails, rerun nnUNetv2_plan_experiment for your dataset. If you use a custom architecture, please downgrade nnU-Net to the version you implemented this or update your implementation + plans.

What exactly should I do? 
Thank you!

**Comment by wasserth** [comment]
This UserWarning happens all the time with nnU-Netv2==2.3.1
It is not the source of the problem.
Can you reinstall in a new environment and also download the new weights?

**Comment by mingtian126** [comment]
Thanks for your quick response! I installed it in a virtual machine under windows system. Are there new version of weights can be downloaded? Thanks!
