### ISSUE TITLE
Why is the rib data only partially marked？

### ISSUE THREAD

**Issue by SummerZ2020** [wasserth/TotalSegmentator#29]
Hello,
Thank you for all your great work.
I found some rib data only partially marked. Was it done on purpose? or just the failed segmentation result？
Thanks a lot

![image](https://user-images.githubusercontent.com/59429566/202951786-5403342b-b9b7-4177-b655-f35a94dcbc9c.png)

**Comment by wasserth** [comment]
The starting point for our rib labels are the segmentations for the ribfracture dataset. Those always excluded the part which is very close to the vertebrae. Therefore this part is always missing.

**Comment by SummerZ2020** [comment]
> Got it. Thx
