### ISSUE TITLE
Incorrect vertebra segmentation

### ISSUE THREAD

**Issue by grinerD** [wasserth/TotalSegmentator#291]
Came across a strange segmentation and was wondering if there was a root cause, or just a hiccup by the model.  Was wondering if anyone has come across something like this.
![image](https://github.com/wasserth/TotalSegmentator/assets/51205859/942de6c3-4d5c-4345-a104-5bc3070dc607)

**Comment by wasserth** [comment]
This mixing of neighouring vertebrae happens in roughly 1-2% of cases. It is a known problem which is not easy to solve unfortunately.
