### ISSUE TITLE
How to train a rough body segmentation model

### ISSUE THREAD

**Issue by Itsanewday** [wasserth/TotalSegmentator#293]
Great work!
Can you disclose more details about training the body model ?

**Comment by mauigna06** [comment]
Hi, thank you for the great work

Do you know if the "body" task will work well with MRIs @wasserth?

**Comment by wasserth** [comment]
The body task only works well for CT images. It was not trained for MR images.

**Comment by LightersWang** [comment]
Hi, thanks for the great work and the body segmentation works very well in our CT images.

Is there any plan to add the MRI body segmentation (task "body_mr") as a new feature for TotalSegmentator?

**Comment by wasserth** [comment]
This is on our agenda. I guess we will finish it within the next 6 months.
