### ISSUE TITLE
Modalities CT/MR and more structures ? 

### ISSUE THREAD

**Issue by Peaceandmaths** [wasserth/TotalSegmentator#296]
Two questions : 

- What should be done to adapt the TS to MRI scans in stead of CT ? 
- Could you add subcortical structures (thalamus, caudate, putamen, pallidum, hippocampus, amygdala, and nucleus accumbens) please ? 

Thanks again for this tool !

**Comment by kulsoom-abdullah** [comment]
> Two questions :
> 
> * What should be done to adapt the TS to MRI scans in stead of CT ?
> * Could you add subcortical structures (thalamus, caudate, putamen, pallidum, hippocampus, amygdala, and nucleus accumbens) please ?
> 
> Thanks again for this tool !

I would also like to use the tool for MRI axial slices, at minimum to segment the vertebrae.  I am trying out preprocessing of the MRI images to where the bones would be easier for the TS model to "see". 

I can work with you and any others on this.

The TS tool is great! So far it has segmented the vertebrae on CT axial slices very well for our use case. @wasserth we appreciate your contribution to the community!

**Comment by wasserth** [comment]
We are currently working on adding support for MRI images and for subcortical structures. But it will take a bit more time.
