### ISSUE TITLE
Could you provide detailed results of different organs? 

### ISSUE THREAD

**Issue by Fivethousand5k** [wasserth/TotalSegmentator#3]
Hi! 
- Could you provide the detailed segmentation results (by value) of different organs?  
- And could you tell us the exact test dataset you used for better comparison?

**Comment by wasserth** [comment]
The train/test/val split can be found in the file `meta.csv` in the dataset which can be downloaded here: https://zenodo.org/record/6802614

What do you mean by detailed segmentation results? Do you mean the softmax probabilities of the nnUNet?

**Comment by Fivethousand5k** [comment]
Hi, I wanna have your numerical metric results such as Dice.  In your current paper, you just provide a figure with metrics plotted, which is hard for us to know the numerical results. Maybe I have to measure these metrics with the help of a ruler. :Þ

**Comment by wasserth** [comment]
I uploaded the detailed results here: https://github.com/wasserth/TotalSegmentator/blob/master/resources/results_all_classes.json
Those are for the high resolution model (1.5mm).

**Comment by Fivethousand5k** [comment]
Thanks
