### ISSUE TITLE
syntax error near unexpected token `(' when executing totalseg_combine_masks

### ISSUE THREAD

**Issue by beantr96** [wasserth/TotalSegmentator#30]
I get the error "syntax error near unexpected token \`('" when combining the masks using totalseg_combine_masks. I found that the issue was caused by missing the line `#!/usr/bin/env python` in `bin/totalseg_combine_masks`. I hope this will be fixed soon in the next stable version. Many thanks ^^

**Comment by wasserth** [comment]
Hi,
thanks for pointing out this bug. The fix is in the master now.
