### ISSUE TITLE
Q: Access TS2 feature maps?

### ISSUE THREAD

**Issue by HendrikBE** [wasserth/TotalSegmentator#300]
Dear all, 

After running an experiment on test data I was surprised by the results, the potential of TS2 is amazing to see! 

I'm trying to access the model layers in order to extract the feature maps. However, I'm having trouble finding the correct way to do this, is someone able to point me in the right direction?

**Comment by HendrikBE** [comment]
> TotalSegmentator is using nnU-Net v2 as a model (https://github.com/MIC-DKFZ/nnUNet). You have to check in the nnU-Net code how to get the feature maps.

Thanks for the response Jakob, I believe https://github.com/MIC-DKFZ/nnUNet/issues/2088 might point me in the right direction. I'll dig into it.

**Comment by Kaihua1203** [comment]
Hi, @HendrikBE,
Have you access the feature maps successfully? I also have this question.
Thanks!
