### ISSUE TITLE
docker contains model parameters?

### ISSUE THREAD

**Issue by jianjun0407** [wasserth/TotalSegmentator#305]
I use the following command, https://github.com/wasserth/TotalSegmentator#run-via-docker, using docker, to call the algorithm.
I have two questions:
First, I found that the size is 27.2G. Is the parameter file of the model included in docker ?
![图片1](https://github.com/wasserth/TotalSegmentator/assets/19251556/fc9b2f49-0f02-4cd6-a294-d70e32592ec3)

Second, I do not find the model parameters file and config.json file on my local computer. If they are included in docker, how can I set "send_usage_stats" to False?

**Comment by wasserth** [comment]
The docker file contains the parameter files. This is one of the reasons for the large size of the docker container. It also contains the config.json file. If you want to set send_usage_stats manually you will either have to adapt the config file right before you call totalsegmentator or you can build the docker container yourself with the adaptations you want. The Dockerfile required to built the container is also in the repository.
