### ISSUE TITLE
Why my segmentations don't seem to be saved？

### ISSUE THREAD

**Issue by DW1003** [wasserth/TotalSegmentator#306]
I followed your tutorial step by step, but the result I got was like the segmentation was not saved。
Here's the statement I typed and the result I got：
You can see that the segmentation is not saved, and I have used the slicer software to see that there is indeed no predicted result, and nothing is displayed.

(d:\totalsegmentotar\.conda) D:\totalsegmentotar>TotalSegmentator -i hip_left.nii.gz -o segmentations -ta hip_implant

If you use this tool please cite: https://pubs.rsna.org/doi/10.1148/ryai.230024

No GPU detected. Running on CPU. This can be very slow. The '--fast' or the `--roi_subset` option can help to reduce runtime.
Generating rough body segmentation...
Resampling...
  Resampled in 1.93s
Predicting...
d:\totalsegmentotar\.conda\Lib\site-packages\nnunetv2\utilities\plans_handling\plans_handler.py:37: UserWarning: Detected old nnU-Net plans format. Attempting to reconstruct network architecture parameters. If this fails, rerun nnUNetv2_plan_experiment for your dataset. If you use a custom architecture, please downgrade nnU-Net to the version you implemented this or update your implementation + plans.
  warnings.warn("Detected old nnU-Net plans format. Attempting to reconstruct network architecture "
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.12it/s]
  Predicted in 12.95s
Resampling...
WARNING: Could not crop because no foreground detected
  cropping from (333, 333, 539) to (333, 333, 539)
Predicting...
d:\totalsegmentotar\.conda\Lib\site-packages\nnunetv2\utilities\plans_handling\plans_handler.py:37: UserWarning: Detected old nnU-Net plans format. Attempting to reconstruct network architecture parameters. If this fails, rerun nnUNetv2_plan_experiment for your dataset. If you use a custom architecture, please downgrade nnU-Net to the version you implemented this or update your implementation + plans.
  warnings.warn("Detected old nnU-Net plans format. Attempting to reconstruct network architecture "
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [04:27<00:00,  4.18s/it]
  Predicted in 288.96s
Saving segmentations...
  0%|                                                                                                                                                             | 0/1 [00:00<?, ?it/s]Creating hip_implant.nii.gz
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:04<00:00,  4.61s/it]
  Saved in 6.80s

**Comment by DW1003** [comment]
If you see please help me, this is very important to me, thank you sincerely.

**Comment by wasserth** [comment]
Does the "total" task work? (`-ta total`)

**Comment by DW1003** [comment]
> Does the "total" task work? (`-ta total`)
You're right, with -ta total, the segmentator progress bar changes, but unfortunately it doesn't seem to save the results of the split, here is my output, and the output folder and the image opened in slicer 5.6.2, and nothing shows up.

![4f9ded52](https://github.com/wasserth/TotalSegmentator/assets/72432230/02fd5704-b014-49dd-9596-b783fab27724)

![980220fe](https://github.com/wasserth/TotalSegmentator/assets/72432230/68c288cd-90a1-4072-871e-0d92c310b889)

**Comment by DW1003** [comment]
> Does the "total" task work? (`-ta total`)

You're right, with -ta total, the segmentator progress bar changes, but unfortunately it doesn't seem to save the results of the split, here is my output, and the output folder and the image opened in slicer 5.6.2, and nothing shows up.

![4f9ded52](https://github.com/wasserth/TotalSegmentator/assets/72432230/1bf9872e-525a-420e-acad-379a6465674d)
![Uploading 1dc142d4.jpg…]()

**Comment by DW1003** [comment]
I'm not sure if it has anything to do with the system, I'm using win11, is the latest version of totalsegmentator a must to use linux? Because I ran into this issue while training nnUNetv2, nnUNetv2 2.3 onwards would get an error.

**Comment by DW1003** [comment]
> I'm not sure if it has anything to do with the system, I'm using win11, is the latest version of totalsegmentator a must to use linux? Because I ran into this issue while training nnUNetv2, nnUNetv2 2.3 onwards would get an error.

I solved this problem! To a large extent it is related to the system, we need linux.

**Comment by panos1998** [comment]
Also iam using ubuntu, from my university hpc cluster, i see in the logs 107 completed extractions of pancreas, but on the same time in the output folder there are only 22 masks saved, the programm has another 300 segmentations to do and is still running. I dont know if finally will save all the segmentations, but could be this an issue?
