### ISSUE TITLE
A specific part of the scapula is never segmented

### ISSUE THREAD

**Issue by mik0699** [wasserth/TotalSegmentator#317]
Hey @wasserth, first of all thanks for your amazing work!
I am using TotalSegmentator to segment scapulae and humeri from 1200 shoulder CTs, but I have this problem. When it comes to the scapula, there is a part of it, called supraspinous fossa, that is never segmented in all of the CTs, while the rest of the bone is well segmented. Here is a screenshot of the 3d rendering of the original CT with the segmentation mask overlapped.
![Issue TotalSegmentator](https://github.com/wasserth/TotalSegmentator/assets/112715293/c0c1fd7c-d0e8-4cfa-9c3a-6aaf26a2287b)
I wanted to ask if you have any idea about the reason of this behavior.

Thanks in advance.

**Comment by wasserth** [comment]
This seems to be a consistent error in the ground truth annotations. We will have to correct this. Until then there is no easy fix unfortunately.

**Comment by mik0699** [comment]
I see, thank you very much for your quick reply!
