### ISSUE TITLE
Segmenting Visceral Fat from CT Files

### ISSUE THREAD

**Issue by itscarolinesong** [wasserth/TotalSegmentator#322]
Hello! 
As far as I know, visceral fat segmentation is currently only available for MR files. Could you clarify if it's possible to perform visceral fat segmentation on CT files as well? 

Thank you in advance!

**Comment by wasserth** [comment]
Yes, this is also possible for CT images. See subtask `tissue_types`.

**Comment by itscarolinesong** [comment]
Just tried it out and it works great! Thank you so much for the quick response!
