### ISSUE TITLE
totalseg contrast phase

### ISSUE THREAD

**Issue by staniPetrox** [wasserth/TotalSegmentator#338]
Hi,

I just found out that you recently pushed the classification for contrast phases (very good idea ;) ). Currently I do not get beyond this point:
`FileNotFoundError: [Errno 2] No such file or directory: 'private/anaconda3/envs/totalsegmentator2.0/lib/python3.10/site-packages/resources/contrast_phase_classifiers.pkl'
`

Can you help me with that?
All the best!

**Comment by wasserth** [comment]
Did you install the latest version from master branch?

**Comment by wasserth** [comment]
I made a new release (2.4.0) which contains the phase classification.
