### ISSUE TITLE
Separating masks in multilabel NIFTI file

### ISSUE THREAD

**Issue by Arconine1** [wasserth/TotalSegmentator#339]
Hi Wasserth,

Thank you for this great open source segmentator, it works well. Just one question: I saved the outputs in a single multilabel .nii file when running it and am now trying to get the masks as separate files. 

Is there any way I can separate the masks within the existing single multilabel NIFTI file? Without having to re-run Totalsegmentator again, this time without the -ml. 

Thank you!

**Comment by wasserth** [comment]
You can manually run some python code or use 3D Slicer to split the multilabel file into single files. TotalSegmentator has to additional command for that.
