### ISSUE TITLE
Task_name headneck_bones_vessels is not functional

### ISSUE THREAD

**Issue by Aakanksha-Rana** [wasserth/TotalSegmentator#342]
Hi, I tried using the -ta headneck_bones_vessels but it is not working.

**Comment by wasserth** [comment]
Probably you need to install a newer version of TotalSegmentator.

**Comment by Aakanksha-Rana** [comment]
Thanks for the response - with the current guideline "pip install TotalSegmentator" in the readme, the oldest version get installed. it would be great to update the readme in this case. Thanks again.
