### ISSUE TITLE
Errors when Training nnUNet with Totalsegmentator

### ISSUE THREAD

**Issue by tedi14** [wasserth/TotalSegmentator#347]
Hello, 

I am at  beginner at Totalsegmentator and I want to train a nnUNet model with your dataset however I am experiencing the following errors when attempting to run the training command,  could you point me to how to fix it? 

![error_training](https://github.com/user-attachments/assets/15dc8c5b-7146-40a8-b576-25d2b298fc96)

Any help will be greatly appreciated! :)

**Comment by tedi14** [comment]
Hi I was also wondering how would I be able to run the training through the GPUs I tried adding cuda device but I am not sure how to order the command so it recognises it?

**Comment by wasserth** [comment]
For question on how to use/train a nnU-Net please refer to the nnU-Net documentation / github page.
