### ISSUE TITLE
Cannot find "brain_structures"

### ISSUE THREAD

**Issue by lwbhahahaha** [wasserth/TotalSegmentator#348]
Hi, I'm trying to do the segmentation task "brain_structures" but I cannot find it in the drop-down list. I already set the license key.

**Comment by wasserth** [comment]
This model is not yet available on totalsegmentator.com or 3D Slicer extension. I will add it there in September. You can only run it when you install TotalSegmentator via pip.

**Comment by lwbhahahaha** [comment]
Hello. I installed Totalsegmentator v2.4.0 via pip. However, I cannot find it in 3D Slicer. Any instructions on how to open Totalsegmentator? Thank you

**Comment by joshy** [comment]
Hey this is the wrong project. The integration with 3D Slicer is here: https://github.com/lassoan/SlicerTotalSegmentatorBest regards,Joshy--Sent from phoneOn 29 Aug 2024, at 21:07, Wenbo Li ***@***.***> wrote:﻿
Hello. I installed Totalsegmentator v2.4.0 via pip. However, I cannot find it in 3D Slicer. Any instructions on how to open Totalsegmentator? Thank you
