### ISSUE TITLE
How to merge ground truth labels to feed nnunet as training samples?

### ISSUE THREAD

**Issue by pooya-mohammadi** [wasserth/TotalSegmentator#350]
First of all, thank you for your great project.
I downloaded totalsegmentator version 2's dataset. I wanted to create a single nifti file as mask image to pass to nnunet but I noticed that there are several overlaps between different classes in one patient's image. 
I want to know how do you tackle this issue. 
Best regards

**Comment by wasserth** [comment]
The following documentation explains this:
https://github.com/wasserth/TotalSegmentator/blob/master/resources/train_nnunet.md

Basically the later labels overwrite the earlier labels when combining them into one file.
