### ISSUE TITLE
How to integrate my model into the Totalsegmentator Run

### ISSUE THREAD

**Issue by tedi14** [wasserth/TotalSegmentator#357]
Hello, 

I have my own trained nnunet model and was able to run predictions on different data. I was wondering where in Totalsegmentator can I find the model itself of Totalsegmentator? Where is it's checkpoint.pth file, folds etc? In which folder is the model itself kept?

Thank you

**Comment by wasserth** [comment]
You need to make edits at several lines in several files if you want to use your own nnU-Net model. Thus, it is not straight forward. I recommend to simply run your nnU-Net independently of TotalSEgmentator.
