### ISSUE TITLE
FutureWarning in predict_from_raw_data

### ISSUE THREAD

**Issue by andersenthomas** [wasserth/TotalSegmentator#359]
There seems to be an update to torch which produces the following warning:

`FutureWarning: You are using torch.load with weights_only=False (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for weights_only will be flipped to True. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via torch.serialization.add_safe_globals. We recommend you start setting weights_only=True for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.`

Maybe an small update?

**Comment by wasserth** [comment]
Thanks for this information. This needs to be updated in the nnU-Net library. Maybe you can post this in https://github.com/MIC-DKFZ/nnUNet
