### ISSUE TITLE
CT skull segmentation fills hole in the skull

### ISSUE THREAD

**Issue by pajdakovicm** [wasserth/TotalSegmentator#362]
Holes are present in my CT scans. However, when I perform a skull segmentation, the holes get filled. Any way to resolve this issue?

**Comment by wasserth** [comment]
Can you post some images? Otherwise I do not really understand what you mean.

**Comment by pajdakovicm** [comment]
The holes are present in images due to the operation that treats subdural hematoma, see attached image. 
I suppose the holes get filled because the training data did not contain such images? 
<img width="659" alt="Screenshot 2024-09-09 at 11 37 15" src="https://github.com/user-attachments/assets/1d877499-ea5f-42db-98bd-084bb0d8c4fc">

**Comment by wasserth** [comment]
Thanks for the image. Your assumption is correct. You could do thresholding within the TotalSegmentator skull mask to get a segmentation where the hole is not filled.

**Comment by pajdakovicm** [comment]
Thank you for your answer. What exactly do you mean by "thresholding within the TotalSegmentator skull mask to get a segmentation" ?
