### ISSUE TITLE
--output_type dicom does not work with --task='body'

### ISSUE THREAD

**Issue by PredExt** [wasserth/TotalSegmentator#363]
When I use --output_type dicom with --task='total' everything seems to work fine.
However when I change to --task='body' I get the following error message:
ValueError: Could not find D:\---\body_trunc.nii.gz. Did you run TotalSegmentator successfully?

Is   --output_type dicom  only for --task='total' ?.

Diallo

**Comment by wasserth** [comment]
You are correct. `--output_type dicom` only works for task total.
