### ISSUE TITLE
【Video courses】Chinese version 3D Slicer TotalSegmentator installation and usage tutorial.

### ISSUE THREAD

**Issue by simzhangbest** [wasserth/TotalSegmentator#364]
Installation:
【使用TotalSegment 模块 在3D Slicer中分割人体所有器官和骨骼】 https://www.bilibili.com/video/BV1m1421m7f2/?share_source=copy_web&vd_source=0e576be21554bb1ea5d13280e520d904
Load local model files:
 【3D Slicer TotalSegmentor 如何本地加载预训练权重】 https://www.bilibili.com/video/BV1aF4m1T73r/?share_source=copy_web&vd_source=0e576be21554bb1ea5d13280e520d904

**Comment by wasserth** [comment]
Nice. Thank you for these tutorials!
