### ISSUE TITLE
Is it Possible to Get Unthresholded Probability Maps in TotalSegmentator?

### ISSUE THREAD

**Issue by langla7** [wasserth/TotalSegmentator#379]
Hello,

I am using the Python API to segment my images, and TotalSegmentator's output provides binary masks. I need to extract isosurfaces from these masks, and to improve the quality of the results, I would like to know if it's possible to obtain the unthresholded probability maps instead of the binary output.

Thank you in advance for your help.

**Comment by wasserth** [comment]
This is not possible at the moment.
