### ISSUE TITLE
Possible to Segment a single organ

### ISSUE THREAD

**Issue by jgmeier511** [wasserth/TotalSegmentator#387]
Hello,

Is there a way to segment a single organ such as the liver or brain?  I am hoping to speed up the segmentation code, rather than use the:

***  --task total 

option which takes a long time.  I am running this on a CPU only system :(.

Thanks!

**Comment by wasserth** [comment]
You can use the option `--roi_subset liver`. For large images this can decrease runtime a lot. For more details please see the documentation.
