### ISSUE TITLE
ModuleNotFoundError: No module named 'totalsegmentatorv2'

### ISSUE THREAD

**Issue by Masaaki-75** [wasserth/TotalSegmentator#389]
I set up my environment following the readme in totalsegmentatorV2: `pip install TotalSegmentator` and was trying to run the python api code:
```python
from totalsegmentatorv2.python_api import totalsegmentator

totalsegmentator(input_path, output_path)
```
but only to get:
```
ModuleNotFoundError: No module named 'totalsegmentatorv2'
```

I also tried installing with 
`pip install git+https://github.com/wasserth/TotalSegmentator.git` but still no luck. So how can i use the pretrained totalsegmentorV2 model to segment my own data?

**Comment by jamesobutler** [comment]
@Masaaki-75 I think you may be confusing this repo for the fork https://github.com/StanfordMIMI/TotalSegmentatorV2/commits/master/ which made edits including renaming the package with v2 in the name.

To run TotalSegmentator v2 of this repo you would pip install any of the versions >= 2. See https://pypi.org/project/TotalSegmentator/#history

To run v1 version of this repo you can follow the instructions at which details installing any of the 1.x versions. https://github.com/wasserth/TotalSegmentator/tree/bde7c9e3925d4b9e7af80922c60f365e0f6a3507?tab=readme-ov-file#running-v1

**Comment by Masaaki-75** [comment]
Ah, that makes sense to me. Thanks!
