### ISSUE TITLE
GPU acceleration on macOS

### ISSUE THREAD

**Issue by lassoan** [wasserth/TotalSegmentator#39]
Many users are asking about GPU acceleration on macOS. Pytorch officially supports MPS acceleration for MacOS 12.3+.  Do you know if there is a plan for nn-unet to support MPS for prediction?

I guess only a number of small changes would be needed at the same places where you added support for CPU for prediction.

**Comment by wasserth** [comment]
I am pretty sure that the nn-unet developers do not have any plans for supporting GPU on MacOS. They also do not have plans to support CPU at the moment. They themselves only use nnU-Net for training and this only makes sense with a big CUDA GPU. Using nnU-Net  for inference on small devices is not on their agenda as far as I can tell. This is unfortunate of course.

**Comment by wasserth** [comment]
They are working on a big rewrite of nnU-Net at the moment. This should be finished soon. But it also will not support CPU. But I hope that the rewrite will be more organised code and therefore it will be easier to make a contribution and add CPU support. But I guess it will take a bit more time until the rewrite of nnU-Net is released.

**Comment by lassoan** [comment]
Thanks a lot for the information. I can understand that developers don't realize just how important it is to able to use AI tools on the end-user's computer, because until I tried TotalSegmentator I did not really care about it either. All AI segmentation tools were clunky, slow, and limited enough so that I did not expect that many end users would have wanted to have them on their computers.

However, TotalSegmentator is completely changed this. It is a very robust and widely applicable tool for end users. I'm not alone. My [post about TotalSegmentator on linkedin](https://www.linkedin.com/posts/andraslasso_this-is-a-game-changer-segment-100-structures-activity-7009167501846609921-Tfdn) generated quite an excitement. It had over 150k impressions in a few days.

TotalSegmentator alone would be enough reason to make nnunet prediction work on multiple devices (CUDA, CPU, MPS). I'll bring this up with DKFZ people at the upcoming [Slicer project week](https://projectweek.na-mic.org/PW38_2023_GranCanaria/). Developers must recognize that they are not the main users of their framework.

**Comment by wasserth** [comment]
I totally agree. I will also push for this with the nnU-Net developers, but it will take a bit.

**Comment by flecot** [comment]
Totally agree with lassoan. TotalSegmentator is a fantastic piece of software and could be made a lot faster for many users by harnessing mac GPU's. Please please please make this happen!

**Comment by jcfr** [comment]
Looking back into this, my understanding is that [wasserth/nnUNet_cust](https://github.com/wasserth/nnUNet_cust) is used internally.

Currently looking in how we could ensure TotalSegmentator works on Apple Silicon, does anyone know what it would take to have it working ? (e.g merge changes from upstream back into `nnUNet_cust` or the version of pytorch used ... )

**Comment by jcfr** [comment]
Thanks for the update. We are looking forward to it.

In the meantime, let us know if you need assistance regarding some of the packaging & distribution challenges related to C++ and/or python packages.

**Comment by wasserth** [comment]
TotalSegmentator v2 is out now and uses nnunet v2 which supports Apple Silicon. However, torch does not yet support apple silicon for 3d convolutions. So we will have to wait until torch adds that.
https://github.com/pytorch/pytorch/issues/77818

**Comment by kritdw** [comment]
Looks like torch has added support now, any chance we can update to use GPU on apple silicon?

**Comment by wasserth** [comment]
They do not support transposed 3D Convs yet, which is needed by nnU-Net: https://github.com/wasserth/TotalSegmentator/issues/250

**Comment by tkerby** [comment]
> They do not support transposed 3D Convs yet, which is needed by nnU-Net: #250

Almost there: https://github.com/pytorch/pytorch/pull/116580

**Comment by cutright** [comment]
> > They do not support transposed 3D Convs yet, which is needed by nnU-Net: #250
> 
> Almost there: [pytorch/pytorch#116580](https://github.com/pytorch/pytorch/pull/116580)

FWIW, I installed the commit from the PR mentioned in the prior comment with:
`pip install git+https://github.com/pytorch/pytorch.git@3c61c525694eca0f895bb01fc67c16793226051a`

Then set the device 'mpu' in my totalsegmentator call and it seems to work.

It took about 8min to get 69 ROIs on a CT sim for a prostate case, using an Apple M2 Pro on Sonoma 14.4 and python 3.10.9. This included DICOM output. I was able to import the DICOM output into my viewer and it looks pretty good to me.

However, I did get several UserWarnings
```
.venv/lib/python3.10/site-packages/nnunetv2/inference/export_prediction.py:67: UserWarning: Cannot set number of intraop threads after parallel work has started or after set_num_threads call when using native parallel backend (Triggered internally at /private/var/folders/s0/mq_8dv3n7d7f8nqltcvp84p40000gn/T/pip-req-build-p_u388oh/aten/src/ATen/ParallelNative.cpp:228.)
  torch.set_num_threads(old_threads)
```
