### ISSUE TITLE
Make rt_utils optional?

### ISSUE THREAD

**Issue by dyollb** [wasserth/TotalSegmentator#395]
`rt_utils` is used to save segmentations as rt-struct. 

Could this be made optional? It introduced a lot of dependencies:

```
rt_utils
# via TotalSegmentator
pathos
#  via rt_utils
opencv-python
#  via rt_utils
dataclasses
#  via rt_utils
ppft
#  via pathos
dill
#  via pathos
pox
#  via pathos
multiprocess
#  via pathos
```

I can offer to submit a PR, e.g. to allow installing TotalSegmentator with or without rt-utils, e.g. with
```
pip install TotalSegmentator[rt]
```

The setup.py could have optional extra requirements:
```py
extras_require={
        "rt": [
            "rt_utils",
        ],
```

Or the setup.py could be replaced by the equivalent setup.cfg or pyproject.toml.

**Comment by dyollb** [comment]
Correction: 
----
I tested removing the dependency and realized that `pathos` is also required by `p-tqdm`, i.e. the gain would be minor unless I would also replace `p_tqdm.p_map` by some equivalent implementation using `tqdm` and `multiprocessing.Pool`. 

This doesn't look too difficult, but I am not sure there is any interest @wasserth ?

**Comment by wasserth** [comment]
Thanks for pointing to these dependencies. Why would you like to avoid them. They are rather small and quick to install.

**Comment by dyollb** [comment]
I am just trying to reduce dependencies. First i thought they were only introduced because of rt-utils.

**Comment by wasserth** [comment]
I agree that less dependencies is nicer, but on the other hand it introduces additional work to avoid them. So for me it is always a trade-off.

**Comment by dyollb** [comment]
one reason to get rid of `pathos` as a dependency is that it seems to be much too strict with its dependency requirements. For example, see this recent diff where all dependencies are bumped (to latest) for no specific reason:

https://github.com/uqfoundation/pathos/commit/33e3f91becf1004e2a5d698ef694dbc393f50e47

**Comment by wasserth** [comment]
I see. I will have a look into it.
