### ISSUE TITLE
Fail to upload file to the website

### ISSUE THREAD

**Issue by blueyo0** [wasserth/TotalSegmentator#4]
Hi, I try to upload NIFTI image (xxx.nii.gz) to https://totalsegmentator.com/. But the uploading process always gets stuck like in the snapshot. 
![snapshotr](https://user-images.githubusercontent.com/30562758/185072528-2c527852-f5b7-43e6-940b-7c58aa175d58.jpg)

**Comment by joshy** [comment]
Hi, thanks for trying out. Can you please provide image that I can test locally?

**Comment by blueyo0** [comment]
Here is the link of my test data (Case from KiTS19)
https://drive.google.com/file/d/1cR7zE-3xJ-by29z5NrJ1ObXD9lkhCOa4/view?usp=sharing

**Comment by joshy** [comment]
It run without problems, maybe try another browser?

![image](https://user-images.githubusercontent.com/170219/185100075-b35be502-08e6-40a9-bac9-0b3910820ade.png)

**Comment by blueyo0** [comment]
Sadly, this issue occurs no matter which brower I chose. Maybe I should check my local network status. Anyway, thank u for the help.
