### ISSUE TITLE
Equivalent for MRI?

### ISSUE THREAD

**Issue by yujanshrestha** [wasserth/TotalSegmentator#40]
Excellent library! Thank you for making this publicly available. I am sure it will accelerate progress in DNN applied to radiological imaging. 

Do you know if there is an equivalent library for MRI? My current thought is to try to convert an MRI to look like a CT scan (in HU) and run TotalSegmentator on the converted image. However, I am having difficulty training such a model from scratch. Do you have any suggestion?

**Comment by wasserth** [comment]
As far as I know there is nothing comparable for MRI images.
Converting MRI images to look like CT images also does not really work well. (segmentation tools do not work well on these converted images)
So unfortunately there is no easy solution for MRI images.

**Comment by yujanshrestha** [comment]
Thank you Jakob
