### ISSUE TITLE
TotalSegmentator: error: argument -ta/--task: invalid choice: 'total_mr'

### ISSUE THREAD

**Issue by shrutiihegde** [wasserth/TotalSegmentator#401]
The MR model used to work fine, thoughts on why I get this error now? The CT model works on the same example.

<img width="1124" alt="Screenshot 2024-12-10 at 2 36 15 PM" src="https://github.com/user-attachments/assets/66e41739-0856-4c77-a0c9-21505a913842">

**Comment by wasserth** [comment]
What do you get if you enter `TotalSegmentator --version`?

**Comment by wasserth** [comment]
This is way too old. You need the newest version.
