### ISSUE TITLE
about the multi phase ct segmentation

### ISSUE THREAD

**Issue by whucsu** [wasserth/TotalSegmentator#404]
thanks for sharing.
I want to check that whether the TotalSegmentator support multi phase ct segmentation.
Because when I load the CT-cardio.seq.nrrd in the 3D Slicer example data, then use the TotalSegmentator module, the system detect the multi phase , but finally slicer give error:import blosc2 ModuleNotFoundError: No module named 'blosc2'.
I need help for two questions: 1) can anyone give suggestions or publication that how does the TotalSegmentator work on multi phase ct segmentation ; 2) since the TotalSegmentator is installed through the extension, then how to solve No module named 'blosc2'.
thanks.

**Comment by wasserth** [comment]
TotalSegmentator should work fine on multi phase ct images. How to solve this 3d Slicer error I do not know. Please ask this question in the 3D Slicer forum.
