### ISSUE TITLE
Total Segmentator not running on GPU in windows

### ISSUE THREAD

**Issue by marco900000** [wasserth/TotalSegmentator#43]
Hi, I’m using Total Segmentator on my laptop (Lenovo Legion) that has an RTX3080 laptop GPU. When I launch it from the windows powershell (and not in Slicer) via the command “python .\TotalSegmentator” it tells me that no GPU is detected and so it runs with the “fast” option. I also installed CUDA 12.0 but it still does not detect the GPU. How can I solve this problem?

**Comment by joshy** [comment]
Hi, have you installed [pytorch](https://pytorch.org/)? Please make sure you install TotalSegmentator in an environment where you also have installed pytorch.

**Comment by marco900000** [comment]
Sure: I installed it using the command “pip3 install torch torchvision torchaudio” as described in this website: https://pytorch.org/
Have I done anything wrong? 
Should I install CUDA too? If so, what version? I installed the 12.0 CUDA version but I don’t know if CUDA is required to run TotalSegmentator and what version

**Comment by marco900000** [comment]
I'm opening the Windows Power Shell, when I do "pip install TotalSegmentator" it tells me: "Requirement already satisfied: TotalSegmentator in c:\users\marcosolbiati\appdata\roaming\python\python39\site-packages (1.4.0)". When I do "pip3 install torch torchvision torchaudio" it tells me "Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: torch in c:\users\marcosolbiati\appdata\roaming\python\python39\site-packages (1.13.1)
Requirement already satisfied: torchvision in c:\users\marcosolbiati\appdata\roaming\python\python39\site-packages (0.14.1)
Requirement already satisfied: torchaudio in c:\users\marcosolbiati\appdata\roaming\python\python39\site-packages (0.13.1)". 
When I try to launch Total Segmentator via the command "python .\TotalSegmentator -i ct.nii.gz -o segmentations" it returns
"C:\Program Files\Python39\python.exe: can't open file 'C:\Users\MarcoSolbiati\TotalSegmentator': [Errno 2] No such file or directory". If I download the repository from this git and I type "cd C:\Users\MarcoSolbiati\Downloads\TotalSegmentator-master\bin" and "python .\TotalSegmentator -i C:\Users\MarcoSolbiati\Desktop\total-segmentator-input.nii -o C:\Users\MarcoSolbiati\Desktop\total-segmentator-out.nii" it tells me "No GPU detected. Running on CPU. This can be very slow. The '--fast' option can help to some extend.
Traceback (most recent call last):
  File "C:\Users\MarcoSolbiati\Downloads\TotalSegmentator-master\bin\TotalSegmentator", line 201, in <module>
    main()
  File "C:\Users\MarcoSolbiati\Downloads\TotalSegmentator-master\bin\TotalSegmentator", line 179, in main
    seg = nnUNet_predict_image(args.input, args.output, task_id, model=model, folds=folds,
TypeError: nnUNet_predict_image() got an unexpected keyword argument 'force_split'". 
How can I launch TotalSegmentator in Windows 10 from command line?
