### ISSUE TITLE
how to use it

### ISSUE THREAD

**Issue by kmordhwaj** [wasserth/TotalSegmentator#44]
How to use it? The documentation of usage is not enough

**Comment by rajanish4** [comment]
I would also like to know how to run the command on command line, the usage is perhaps not clear. Please let me know if anyone knows about this

**Comment by wasserth** [comment]
The useage is completely explained in the documentation (https://github.com/wasserth/TotalSegmentator#usage). If you are not familiar with the usage of the command line I would recommend to do a tutorial on command line usage first and then the documentation of TotalSegmentator will make sense to you.

**Comment by wasserth** [comment]
Otherwise you can simply try our online version: https://totalsegmentator.com/

**Comment by rajanish4** [comment]
The error that i get on command line is this: 'TotalSegmentator' is not recognized as an internal or external command,
operable program or batch file. 
I have pip installed the package and yet i get this error on my anaconda prompt. That is the reason i wanted to know how it could be installed as cmd command. Please let me know.

**Comment by kmordhwaj** [comment]
@rajanish4 I had a successful run last evening. I will share the steps to be followed after some hours.

**Comment by rajanish4** [comment]
@kmordhwaj Ok let me know please

**Comment by kmordhwaj** [comment]
you have to use it in git bash and with CPU option (in majority cases we don't have good GPU in our laptop)

Follow these steps: (assuming you have windows)

1. Download and Install python
   https://www.python.org/downloads/
  (don't forgot to select path environment on installation)

2. Download and install git (it will add git bash command shell)
   https://gitforwindows.org/

3. Download and install anaconda for windows
   https://www.anaconda.com/products/distribution

4. Open Git Bash
   run "conda init bash"
   
5. Reopen Git Bash and you should see (base) in the first line
   run "ipython"

6. install pytorch with cpu option
  run "conda install pytorch torchvision torchaudio cpuonly -c pytorch" in Git Bash
 then run "pip install torch"

7. install totalsegmentator
   run "pip install TotalSegmentator" in git bash (in folder path you wanna install) (e.g. c:/users/kmord/Desktop/totalseg)

8. then move a nifty file renamed as "ct.nii.gz" in the same folder totalseg
    then with git bash run in same path (c://users/kmord/Desktop/totalseg)
   "TotalSegmentator -i ct.nii.gz -o . --fast"
   here -i is command for input
  here -o is command for output
  ct.nii.gz (file name is "ct" with extension ".nii.gz") should present in same folder (path) where the above command is going to run
  -o . (here . is for "all", means we want to save our output 104 segments nifti files in the same folder)
--fast is a tag for fast processing (as we don't have gpu, and running pytorch with cpu)

Thanks.
It should work now.

**Comment by kmordhwaj** [comment]
if you already had installed pytorch with cuda then don't forget to uninstall it before installing with cpu option

`conda uninstall pytorch`
`pip uninstall torch`

**Comment by rajanish4** [comment]
Thanks a lot, i will give it a try :)

**Comment by marco900000** [comment]
Hi @kmordhwaj I followed your bulltpoints but the error that I get when I do TotalSegmentator -i ct.nii.gz -o . —fast is “TotalSegmentator is not defined”. Do you know why?

**Comment by kmordhwaj** [comment]
Hlw @marco900000 ,
do check if the TotalSegmentator installed.

run `pip list` 
A. If you are able to see TotalSegmentator in the list, then it's installed (may be globally or on current directory's virtual 
    environment).
    then try again `TotalSegmentator -i ct.nii.gz -o . —fast`
    If the error is same "TotalSegmentator is not defined" then obviously the TotalSegmentator is installed globally.
   
   try to run it in virtual environment
   1. Open any command prompt
       Open any directory (let it's desktop) (c:/users/kmord/Desktop)

   2. Make a new folder
       c:/users/kmord/Desktop/`mkdir test`

   3. Move inside that folder
       c:/users/kmord/Desktop/`cd test`

   4. Make a virtual environment using python (first check if python and pip available - run `python --version` and `pip --version`)
   (also check it's python or python3 - run `python` if you are now able to perform code in terminal then it is python. Similarly you can check for run `python3`
   c:/users/kmord/Desktop/test/`python -m venv .`  (we are making a virtual environment named test in test folder)

  5. Now activate virtual environment
   c:/users/kmord/Desktop/test/`./Scripts/activate`
  now if the path is
  (test) c:/users/kmord/test/
  then your virtual env is activated (note- can run `deactivate` to come out of any virtual env)

 6. Now install Total segmentator
  (test) c:/users/kmord/test/`pip install TotalSegmentator`
  (i). If it's installed then you are all set to run `TotalSegmentator -i ct.nii.gz -o . —fast` (if ct.nii.gz file is in test folder and you want to download all 104 segments on the test folder)
  (test) c:/users/kmord/test/`TotalSegmentator -i ct.nii.gz -o . —fast`
  (ii). If it's not installed then there may be possible error "SimpleITK==2.0.2" dependency issue 
   you need to downgrade python version 
    - uninstall python from installed apps of the system
    - install python version 3.10.2  [https://python.en.uptodown.com/windows/download/4271623](url)
    - perform all above tasks


B. If the pip list doesn't contain TotalSegmentator then can try `pip install TotalSegmentator` and then run that above segmentation command.

Thankyou.
write back if you get stuck again.

**Comment by marco900000** [comment]
Dear @kmordhwaj thank you for your help. 
When I run pip list I see TotalSegmentator listed but when I run the TotalSegmentator I still get the error “TotalSegmentator is not recognized as an internal or external command”. I have created the virtual environment that you suggested and it goes smooth until point 6 of your list. It installs TotalSegmentator correctly (if I run pip list in the virtual environment I see it) but when I then run (test) c:/users/kmord/test/TotalSegmentator -i ct.nii.gz -o . —fast it tells me “TotalSegmentator is not recognized as an internal or external command.”. I have python 3.9.7 version installed.
Can you help me with this? 
thank you so much

**Comment by kmordhwaj** [comment]
@marco900000 
may be you have some more environment in your system and may be you are inside that environment where total segmentator is not installed. You should deactivated from that other virtual environments.
make sure while running that totalsegmentator command

`(base)
kmord@DESKTOP-460L01F MINGW64 ~/Desktop/inzint/gtf/segments
$ TotalSegmentator -i ct.nii.gz -o . --fast


Please cite the following paper when using nnUNet:

Isensee, F., Jaeger, P.F., Kohl, S.A.A. et al. "nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation." Nat Methods (2020). https://doi.org/10.1038/s41592-020-01008-z


If you have questions or suggestions, feel free to open an issue at https://github.com/MIC-DKFZ/nnUNet

preprocessing C:\Users\kmord\AppData\Local\Temp\nnunet_tmp_7ej9lxvv\s01.nii.gz
using preprocessor GenericPreprocessor
before crop: (1, 61, 73, 61) after crop: (1, 61, 73, 61) spacing: [3. 3. 3.]

no resampling necessary
no resampling necessary
before: {'spacing': array([3., 3., 3.]), 'spacing_transposed': array([3., 3., 3.]), 'data.shape (data is transposed)': (1, 61, 73, 61)}
after:  {'spacing': array([3., 3., 3.]), 'data.shape (data is resampled)': (1, 61, 73, 61)}

(1, 61, 73, 61)
This worker has ended successfully, no errors to report
C:\Users\kmord\anaconda3\lib\site-packages\torch\cuda\amp\grad_scaler.py:118: UserWarning: torch.cuda.amp.GradScaler is enabled, but CUDA is not available.  Disabling.
  warnings.warn("torch.cuda.amp.GradScaler is enabled, but CUDA is not available.  Disabling.")
C:\Users\kmord\anaconda3\lib\site-packages\torch\amp\autocast_mode.py:202: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
  warnings.warn('User provided device_type of \'cuda\', but CUDA is not available. Disabling')


Please cite the following paper when using nnUNet:

Isensee, F., Jaeger, P.F., Kohl, S.A.A. et al. "nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation." Nat Methods (2020). https://doi.org/10.1038/s41592-020-01008-z


If you have questions or suggestions, feel free to open an issue at https://github.com/MIC-DKFZ/nnUNet

force_separate_z: None interpolation order: 0
No GPU detected. Running on CPU. This can be very slow. The '--fast' option can help to some extend.
Using 'fast' option: resampling to lower resolution (3mm)
Resampling...
  Resampled in 0.10s
Predicting...
  Predicted in 12.43s
Resampling...
Saving segmentations...
100%|##########| 104/104 [00:07<00:00, 14.02it/s]
  Saved in 8.34s
(base)
kmord@DESKTOP-460L01F MINGW64 ~/Desktop/inzint/gtf/segments
$
`

**Comment by kmordhwaj** [comment]
Hi @marco900000 

Try this ->
1. Open git bash
2. Go to that test directory (in my case its c://users/kmord/Desktop/test2/store)
   (base) c:/users/kmord/`cd Desktop`
   (base) c:/users/kmord/Destop/`cd test2`
   (base) c:/users/kmord/Desktop/test2/`cd store`
3. Run that command (make sure ct.nii.gz which is input is in test folder)
   (base) c:/users/kmord/Desktop/test2/store/TotalSegmentator -i ct.nii.gz -o . --fast

its working for me

<img width="454" alt="2023-01-02-1" src="https://user-images.githubusercontent.com/109667137/210197852-48d60c2d-40a4-4055-80f2-1cee0a566fff.png">

<img width="450" alt="2023-01-02-2" src="https://user-images.githubusercontent.com/109667137/210197854-061fb08c-52fd-4198-a2c2-bab6f4407711.png">

**Comment by marco900000** [comment]
Dear @kmordhwaj I did that but the output is always the same: "TotalSegmentator is not recognized as an internal or external command". Can you @wasserth help in this? I followed your guide: 
- Installed Python 3.8.10  for all users adding it to PATH in installation
- Installed CUDA 11.6 toolkit
- Installed Pytorch with the command: "pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu116"  and I have done all the verifications as described here: https://pytorch.org/get-started/locally/ and everything works
- Added in PATH environmental variable "C:\Users\MarcoSolbiati\AppData\Roaming\Python\Python38\Scripts"
- Opened terminal and installed TotalSegmentator with: pip install TotalSegmentator.
The output of "pip list" is as you can see in the image: 
<img width="532" alt="cmd1" src="https://user-images.githubusercontent.com/121352611/210211997-9a603c39-f1c7-4e6c-a996-4bbee0e402ea.png">
<img width="968" alt="cmd2" src="https://user-images.githubusercontent.com/121352611/210212020-e9d1308a-802e-4a84-9d64-440b17897622.png">
But when I run in a standard cmd the command "TotalSegmentator -i C:\Users\MarcoSolbiati\Desktop\total-segmentator-input.nii -o C:\Users\MarcoSolbiati\Desktop\total-segmentator-output.nii --fast" I always get this error: 'TotalSegmentator' is not recognized as an internal or external command,
operable program or batch file.
What can be the problem @wasserth ? Thank you for your help

**Comment by kmordhwaj** [comment]
@marco900000  can you show the results of `pip list` when running on path  C:\Users\MarcoSolbiati\Desktop\`pip list` where you are running that processing code

**Comment by marco900000** [comment]
Dear @kmordhwaj thank you again for the help. I have done "cd C:\Users\MarcoSolbiati\Desktop\" and then "pip list" and this is the result: 
<img width="403" alt="cmd1" src="https://user-images.githubusercontent.com/121352611/210221317-619da193-36d2-4ca7-84c1-5004a419ff8c.png">

<img width="638" alt="cmd2" src="https://user-images.githubusercontent.com/121352611/210221322-e732295f-7dd6-4fe8-a5df-bd4271329931.png">

Let me know your thoughts thanks

**Comment by kmordhwaj** [comment]
hi @marco900000 please give a try with git bash not command prompt. I also was not able to get results when running from command prompt and from vs code. But strangely it's working with Git Bash.

**Comment by marco900000** [comment]
I did the same with Git Bash. The output of "pip list" is the same as with the command prompt while the error that I get when running TotalSegmentator is different: "bash:/c/Users/MarcoSolbiati/AppData/Roaming/Python/Python38/Scripts/TotalSegmentator: c:\program: bad interpreter: No such file or directory". 
<img width="457" alt="bash" src="https://user-images.githubusercontent.com/121352611/210227292-f5df03a8-0ca4-4f01-b790-9065430f41b2.png">

@kmordhwaj @wasserth can you help with this?

**Comment by kmordhwaj** [comment]
@marco900000 please see my code in bash and yours. You are not getting (base). As I can see you are running from c:/users/MarcoSolbiati so put a nifti file in your MarcoSolbiati folder and rename that nifti file to "ct.nii.gz" and then run `TotalSegmentator -i ct.nii.gz -o . --fast`

**Comment by xiaoli26** [comment]
I ran into the same problem and  I tried the git bash and typed "where totalsegmentator" and got the result:
$ where totalsegmentator
D:\Users\omnisky\AppData\Local\slicer.org\Slicer 5.3.0-2023-04-09\lib\Python\Scripts\TotalSegmentator
C:\Users\omnisky\AppData\Roaming\Python\Python310\Scripts\TotalSegmentator
(base)

so I delete the former Path for Slicer-TotalSegmentator and came into the error below:

OMP: Error #15: Initializing libiomp5md.dll, but found libiomp5md.dll already initialized.
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.
(base)

I finally delete the libiomp5md.dll under the folder "D:\ProgramData\anaconda3\Library\bin" and everything went well.

Thanks for sharing and hope this can help people who came into the same problem as me.
