### ISSUE TITLE
Is skin segmentation possible?

### ISSUE THREAD

**Issue by ponvthc** [wasserth/TotalSegmentator#45]
I realize that this is a feature request, but I'm interested in performing a project looking at needle targeting from the body wall to a region of interest, and wondered if any work has been previously done to segment the body wall? Thanks!

**Comment by wasserth** [comment]
What do you exactly mean by body wall? Only the skin or also some more layers e.g. subcutaneous fat?

**Comment by ponvthc** [comment]
Skin only would work fine for my purposes.

**Comment by wasserth** [comment]
I will add a model for segmentation of the entire body soon. You could then use the outer 2 or 3 voxels of this mask as an approximation of the skin.

**Comment by wasserth** [comment]
I added a model for body and skin segmentation now. It is available in the latest master. You use it the following way:

```
TotalSegmentator -i ct.nii.gz -o seg --fast
TotalSegmentator -i ct.nii.gz -o seg -ta body
```
Then you will have a file "skin.nii.gz" in the output folder.
