### ISSUE TITLE
How to speedup first invocation

### ISSUE THREAD

**Issue by marco900000** [wasserth/TotalSegmentator#49]
When I run TotalSegmentator from command line in Windows 10 for the first time it runs very slow. This does not happen if I run it a second or third time provided that I don't turn off the PC. This is supposedly because it creates temp files that are deleted when the PC is turned off. If this is the case, is it possibile to change the location of these temp files so that they remain when the PC is turned off and then back on so that the first time invocation of TotalSegmentator runs faster? @wasserth

**Comment by wasserth** [comment]
This sounds a bit strange. I am not aware of any temp file which could be the reason for this. And I am not very familiar with windows. 
You could try different versions of TotalSegmentator and see if it was introduced with a certain version.

**Comment by marco900000** [comment]
For example the folder nnunet_tmp_9y890y6x is created by TotalSegmentator in the folder C:\Users\User\AppData\Local\Temp.

**Comment by wasserth** [comment]
For each prediction there is a new temp folder created. This should not be any slower the first time you call it.
I guess the slow speed has some other reason, not the temp folders.

**Comment by marco900000** [comment]
Thank you very much @wasserth. I’ll try to dig into it
