### ISSUE TITLE
Direction inconsistency of some images and labels

### ISSUE THREAD

**Issue by Fivethousand5k** [wasserth/TotalSegmentator#5]
Hi! I note there is an inconsistency in some image files and label files.
Take s0000 as an example:
```import SimpleITK as sitk

s0000_image_path = "./s0000/ct.nii.gz"
s0000_label_path = "./s0000/segmentations/adrenal_gland_left.nii.gz"

img_itk = sitk.ReadImage(s0000_image_path)
img_spacing = img_itk.GetSpacing()
img_origin = img_itk.GetOrigin()
img_direction = img_itk.GetDirection()

label_itk = sitk.ReadImage(s0000_label_path)
label_spacing = label_itk.GetSpacing()
label_origin = label_itk.GetOrigin()
label_direction = label_itk.GetDirection()
print(img_direction)
print(label_direction)
```

And the outputs of img_direction and label_direction are ```(-0.9490937598680198, -0.3147874668791464, 0.0, 0.3149937062539274, -0.9491621835575891, 0.0, 0.0, 0.0, 1.0)``` and ```(-0.9491279802851124, -0.3148905736175017, 0.0, 0.31489057947151006, -0.9491279822272867, 0.0, 0.0, 0.0, 1.0)``` respectively.

But for some other samples such as s0006,  the img_direction and label_direction are the same.

I wonder why this is the case. Thank you!

**Comment by wasserth** [comment]
This is some float precision issue I guess. If you simply round all numbers to three decimal places the directions should be identical for image and label file.

**Comment by Fivethousand5k** [comment]
Ok，I reset all of them with the same direction (-1.0, 0.0, 0.0, 0.0, -1.0, 0.0, 0.0, 0.0, 1.0).
