### ISSUE TITLE
totalsegmentator.com doesn't work

### ISSUE THREAD

**Issue by mauigna06** [wasserth/TotalSegmentator#50]
Hi Jakob

Thank you for such a great project

Just wanted to let you know that like since 2 months `totalsegmentator.com` never finishes uploading the CT but I tested on docker and on SlicerTotalSegmentator and it works really well

**Comment by joshy** [comment]
Hi Mauro,

thanks for trying out totalsegmentator.com. The website is not working for very large CT images. See this [comment](https://github.com/wasserth/TotalSegmentator/issues/42#issuecomment-1367209128). If the images are smaller and you can share the dataset I can try to investigate what might be the problem.

**Comment by ValentinKoch** [comment]
Same for me, maybe change the description of the website that says 500mb is the upper limit? What would be the actual upper limit in size? Thanks :)

**Comment by joshy** [comment]
Now the limit is set to 100MB
