### ISSUE TITLE
it is giving strange error

### ISSUE THREAD

**Issue by kmordhwaj** [wasserth/TotalSegmentator#52]
File "/home/ubuntu/segserver/venv/bin/TotalSegmentator", line 14, in <module>
    from totalsegmentator.preview import generate_preview
  File "/home/ubuntu/segserver/venv/lib/python3.10/site-packages/totalsegmentator/preview.py", line 11, in <module>
    from fury import window, actor, ui, io, utils
  File "/home/ubuntu/segserver/venv/lib/python3.10/site-packages/fury/window.py", line 12, in <module>
    from fury.interactor import CustomInteractorStyle
  File "/home/ubuntu/segserver/venv/lib/python3.10/site-packages/fury/interactor.py", line 7, in <module>
    from fury.lib import (Command, InteractorStyleUser, InteractorStyleImage,
  File "/home/ubuntu/segserver/venv/lib/python3.10/site-packages/fury/lib.py", line 7, in <module>
    import vtkmodules.vtkDomainsChemistryOpenGL2 as dcovtk
ImportError: libGL.so.1: cannot open shared object file: No such file or directory

**Comment by wasserth** [comment]
Could you show what `pip list` is printing out?

Moreover, does it work if you do not use the option `--preview`?

**Comment by kmordhwaj** [comment]
yes sir


Send2Trash                    1.8.0
service-identity              18.1.0
setuptools                    63.4.1
SimpleITK                     2.0.2
sip                           4.19.13
six                           1.16.0
sklearn                       0.0.post1
smart-open                    5.2.1
sniffio                       1.2.0
snowballstemmer               2.2.0
sortedcollections             2.1.0
sortedcontainers              2.4.0
soupsieve                     2.3.1
Sphinx                        5.0.2
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
spyder                        5.2.2
spyder-kernels                2.2.1
SQLAlchemy                    1.4.39
sqlparse                      0.4.3
statsmodels                   0.13.2
sympy                         1.10.1
tables                        3.6.1
tabulate                      0.8.10
TBB                           0.2
tblib                         1.7.0
tenacity                      8.0.1
terminado                     0.13.1
testpath                      0.6.0
text-unidecode                1.3
textdistance                  4.2.1
threadpoolctl                 2.2.0
three-merge                   0.1.1
tifffile                      2021.7.2
tinycss                       0.4
tldextract                    3.2.0
toml                          0.10.2
tomli                         2.0.1
tomlkit                       0.11.1
toolz                         0.11.2
torch                         1.13.1
torchaudio                    0.13.1
torchvision                   0.14.1
tornado                       6.1
TotalSegmentator              1.4.0

**Comment by kmordhwaj** [comment]
I tried even TotalSegmentator==1.5.2 and TotalSegmentator==1.5

It was giving same error

It was working fine someday back

**Comment by kmordhwaj** [comment]
I am not using --preview tag

I am using "TotalSegmentator -i ct.nii.gz -o . --fast" only

**Comment by wasserth** [comment]
fury is not in your list of installed packages. Therefore it does not work I guess.

**Comment by kmordhwaj** [comment]
I resolved it @wasserth 
thanks.
I had used
`sudo apt-get install ffmpeg libsm6 libxext6  -y`
