### ISSUE TITLE
Liver vessels segmentation 

### ISSUE THREAD

**Issue by marco900000** [wasserth/TotalSegmentator#53]
Hi Jakob, 

Can you make also the segmentation of liver vessels? That would be a great add-on. @wasserth

**Comment by marco900000** [comment]
Dear Jakob @wasserth how can I send the dicom with annotations to you?

**Comment by wasserth** [comment]
I would need nifti files. Can you convert the dicom annotations to nifti files? Then upload them to any online storage (e.g. dropbox or google drive) and share the link with me.

**Comment by marco900000** [comment]
Sure: I can do that. I will paste the link in this issue. Is it ok for you?

**Comment by wasserth** [comment]
Sure. Or you can send to me via email: jakob.wasserthal@usb.ch

**Comment by delton137** [comment]
In case you don't already know - there's a lot of liver vessels data available from the [Medical Segmentation Decathalon](http://medicaldecathlon.com/) (click on "get data" and download Task08_HepaticVessel.tar)

**Comment by wasserth** [comment]
Thanks for pointing to this. I must have overlooked this task in the decathlon. This make things a lot easier.

**Comment by marco900000** [comment]
Dear @wasserth I have just send you an email with the dataset as you requested
