### ISSUE TITLE
Evaluation

### ISSUE THREAD

**Issue by naayem** [wasserth/TotalSegmentator#55]
Hello and thank you for the great work!

Can you provide the code you used to perform the evaluation of the model? I would like to replicate that and do experimentations for a paper.

Incidentally, do you know if it is easy to you a pretrained nnUnet (on BTCV for example) and use its weights to on an new task for Totalsegmentor dataset?

Bests,
Vincent

**Comment by wasserth** [comment]
Please see this link for more details for evaluation: https://github.com/wasserth/TotalSegmentator#train--validation--test-split

**Comment by naayem** [comment]
So for the pre-training question, it is well answered in here:  https://github.com/MIC-DKFZ/nnUNet/issues/1108#issuecomment-1231467206

Exactly, so my question was if you could provide your code to aggregate results across subjects and classes the following approach was taken: For each class in each subject calculate the (Dice) score, then take the average of all scores (micro averaging). If a class is not present on an image (e.g. the brain is not present on images of the legs) then exclude this value from the calculation.

But otherwise I can do it and maybe share it in here. Or maybe it's done by nnUnet I didn't check yet.

**Comment by qianxingyucode** [comment]
@naayem Hi, have you ever found a evaluation pipeline? I would like to evaluate totalsegmentator in some public datasets, but I do not know how to start. Could you please offer some tips or any code ?
