### ISSUE TITLE
Labeling of coronary arteries

### ISSUE THREAD

**Issue by francescopisu** [wasserth/TotalSegmentator#59]
Hello, thank you for the great package!

I successfully segmented the coronary arteries in one of my CTA cases, but I was wondering if there was a way to obtain different segmentations for the different arteries (e.g., RCA, LCX, etc).
If not, what should be a starting point to tackle this problem ?

Thank you,

Francesco

**Comment by wasserth** [comment]
So far there is no way to get the different arteries. You can try to split it up by some postprocessing logic. Maybe looking at the proximity to the different heart chambers. But this could be a bit tricky.
