### ISSUE TITLE
where to find Task25*_TotalSegmentator_*.py for nnUNet/nnunet/dataset_conversion

### ISSUE THREAD

**Issue by mcastrorennes** [wasserth/TotalSegmentator#65]
Hi, 

Could you provide us the phyton file "ask25*_TotalSegmentator_*.py" so we can retrain the model on our own.

Thank

**Comment by wasserth** [comment]
There is not such a file. I use the function "combine_masks_to_multilabel_file" in https://github.com/wasserth/TotalSegmentator/blob/master/totalsegmentator/libs.py and a bit of custom python code to transform the data into the correct format for a nnunet training.
