### ISSUE TITLE
Possibility to run Total Segmentator V2

### ISSUE THREAD

**Issue by lauraguilevy** [wasserth/TotalSegmentator#66]
Hi,

Thanks a lot for this great package. Would it be possible to obtain a segmentation for the extended set of labels (120) mentioned in your label table (README file), also present in the class_map dictionary at key "total_v2", namely including tibia and extremities (phalanges_hand), etc? 
Thanks in advance!

**Comment by wasserth** [comment]
I am currently working on this. Should be released soon!

**Comment by lauraguilevy** [comment]
Thanks, great news! Looking forward to the new version!
