### ISSUE TITLE
Skin and body outputs are not declared for "body" task

### ISSUE THREAD

**Issue by lassoan** [wasserth/TotalSegmentator#67]
When using the `body` task then the network computes 4 segments:
- skin.nii.gz
- body.nii.gz
- body_trunc.nii.gz
- body_extremities.nii.gz

However, in the class map only "body_trunc" and "body_extremities" show up:

https://github.com/wasserth/TotalSegmentator/blob/af44342d7b5a7f6331b33b26434b58882871a68a/totalsegmentator/map_to_binary.py#L311-L313

Is this just a bug or we should get the list of segments a task produces in some other way?

**Comment by pieper** [comment]
@wasserth you mentioned you embed the label names and values in an xml adjunct to the nii.gz files when working with Nora - can you point to any descriptions of this?

**Comment by wasserth** [comment]
`skin.nii.gz` and `body.nii.gz` are derived via some simple postprocessing from `body_trunc.nii.gz` and `body_extremities.nii.gz`. The dictionaries in `map_to_binary.py` only contain the classes which are the output from the nnU-Net. This happens here: https://github.com/wasserth/TotalSegmentator/blob/master/totalsegmentator/nnunet.py#L337

At the moment you would have to look at this part of the code to find it out. I could add an additional dictionary for classes after postprocessing in `map_to_binary.py` if that helps.

**Comment by wasserth** [comment]
@pieper reading and writing this extended header is done here: https://github.com/wasserth/TotalSegmentator/blob/master/totalsegmentator/nifti_ext_header.py

**Comment by lassoan** [comment]
Thank you for the explanation, then we just keep importing these two segments. Is it possible to disable generation of these extra segments (just to avoid unnecessary computations)?

**Comment by lassoan** [comment]
If users find the derived segments useful and especially if computation of the derived segments is not trivial, then it would be useful to have the additional dictionary that includes the post-processing results.

**Comment by wasserth** [comment]
At the moment it is not possible to disable the generation. It does not take a lot of time. I try not to add too many command line arguments otherwise it starts getting confusing.
