### ISSUE TITLE
--roi_subset is unrecognized

### ISSUE THREAD

**Issue by lammour** [wasserth/TotalSegmentator#69]
Hello and thank you for this work,

From the documentation, the advanced setting --roi_subset should be available:

> `--roi_subset`: Takes a space separated list of class names (e.g. spleen colon brain) and only saves those classes. Saves runtime during saving of nifti files.

I installed TotalSegmentator from pip and this option seems missing:

>TotalSegmentator: error: unrecognized arguments: --roi_subset spleen 

Did I get it wrong?

**Comment by wasserth** [comment]
This is only available in the lastest master branch so far. You can install it the following way:
https://github.com/wasserth/TotalSegmentator#install-latest-master-branch-contains-latest-bug-fixes

**Comment by lammour** [comment]
Thanks a lot, it works fine and reduced my total execution time by approximately 40%!
