### ISSUE TITLE
Bug in undo canonical

### ISSUE THREAD

**Issue by YingdaXia** [wasserth/TotalSegmentator#7]
Thanks for your perfect project! Your project will be a major milestone.

One possible bug in `TotalSegmentator/totalsegmentator/nnunet.py` line 189:

I changed into:
`undo_canonical_nifti(tmp_dir / "s01.nii.gz", file_in, tmp_dir / "s01.nii.gz")`

This will fix the issue of the direction inconsistency between the image input and the segmentation output.

Please kindly check on it and see if this makes sense. Thanks!

**Comment by wasserth** [comment]
Thank you for pointing this out. That was indeed a bug. I just pushed a fix.
