### ISSUE TITLE
Outputs of lung vessel segmentation

### ISSUE THREAD

**Issue by Chen-Jxiang** [wasserth/TotalSegmentator#71]
Hi,

    I noticed that when I run the lung vessel segmentation, I got a mask that contains small real values (~10^-7 - 10^-2). What do these values mean? If I want to get a binary mask, how should I choose the threshold?

Thanks,
Junxiang

**Comment by wasserth** [comment]
That is strange. You can threshold the mask at 0.5 to get a binary mask.

**Comment by Chen-Jxiang** [comment]
OK. If I use other thresholds like 5^-5, the mask looks reasonable. However, if I use 0.5, none of the points in the image is above the thresholds.

**Comment by wasserth** [comment]
What is the command you are using to call TotalSegmentator?

**Comment by Chen-Jxiang** [comment]
This is how I call TotalSegmentor:
    TotalSegmentator -i [filename] --fast -o [output]
    TotalSegmentator -i [filename] -ta lung_vessels -o [output]

**Comment by wasserth** [comment]
This works fine for me and the output mask (`lung_vessels.nii.gz`) is a binary mask with 0 and 1.
