### ISSUE TITLE
Update nnunet-customized to use scikit-learn instead of sklearn

### ISSUE THREAD

**Issue by lwjason** [wasserth/TotalSegmentator#72]
Hi @wasserth , thanks for the excellent project! I recently encountered an error when installing TotalSegmentator. After digging into it, it turns out that nnunet installed sklearn instead of scikit-learn. 

It got fixed two days ago in the original repo https://github.com/MIC-DKFZ/nnUNet/pull/1209#issuecomment-1426233399 but if I understand it correctly, it is needed to update that in the fork as well.

**Comment by wasserth** [comment]
In the custom fork of TotalSegmentator this should already be fine: https://github.com/wasserth/nnUNet_cust/blob/working_2022_03_18/setup.py

Maybe the error has some different reason?

**Comment by wasserth** [comment]
That was a good hint. The change was part of the nnunet_cust masterbranch but not part of the pip package yet. I updated it now. Could you try again with the latest TotalSegmentator master?
```
pip install git+https://github.com/wasserth/TotalSegmentator.git
```

**Comment by aledelmo** [comment]
It seems to work for me, sklearn requirements is now gone
`Requires: batchgenerators, dicom2nifti, medpy, nibabel, pandas, requests, scikit-image, scikit-learn, scipy, SimpleITK, tifffile, torch, tqdm`
Thank you ! Exceptional project!

**Comment by lwjason** [comment]
Thank you! It works perfect now 👍

**Comment by yashindc** [comment]
Hi @wasserth , first of all, thank you for this excellent contribution.
Unfortunately, I hit the same problem with sklearn when installing from pip with: `pip install TotalSegmentator`. The version that gets installed is 1.5.2 and I can see that is prior to this fix.
Is it possible to release a new version with this fix?

Thank you very much in advance!

**Comment by gediminasz** [comment]
I can confirm the latest version in PyPI is broken. A new version release would be greatly appreciated!
