### ISSUE TITLE
Suppress output of nnunet-customized

### ISSUE THREAD

**Issue by CarloPoletto** [wasserth/TotalSegmentator#73]
I'm developing a python application that uses TotalSegmentator. This works very well but I noticed that the nnunet-customized library generates a lot of text output on the console even with the use of the `--quiet` parameter for the TotalSegmentator script. Taking a look at the python code, I realized that this is due to the use of multiprocessing. Since it seems to me that the nnunet-customized library is a fork of nnunet specifically made for TotalSegmentator, is it possible to create a patch to totally mute that library?

**Comment by wasserth** [comment]
I am hoping to merge to the original nnunet in the future. Therefore I am hesitant to make many changes to my nnunet fork. Normally the --quiet option should work.

**Comment by wasserth** [comment]
TotalSegmentator v2 uses the original nnunet (v2) now.
