### ISSUE TITLE
Easy step by step directions to utilize TotalSegmentator

### ISSUE THREAD

**Issue by EnioMDMPH** [wasserth/TotalSegmentator#74]
First and foremost forgive my novice. I'm an MD with a small computer programing background interested in utilizing TotalSegmentator as part of a separate research project.  Goal is to incorporate it as part of a separate process. Is there somewhere with easy step by step instructions on how to segment a folder containing a set of DICOM files through the program?

**Comment by wasserth** [comment]
Unfortunately there is no step by step instructions for this.
Basically you first have to convert the DICOM to nifti using e.g. the dcm2niix library.
Then you have to run TotalSegmentator.
To do this automatically for all subjects in the directory it would make sense to use a scripting language like Bash or Python.

**Comment by lassoan** [comment]
We created a 3D Slicer extension to make TotalSegmentator easily usable for clinicians. It requires only a few button clicks to install and run it on any DICOM image. See step-by-step instructions here: https://github.com/lassoan/SlicerTotalSegmentator#totalsegmentator

**Comment by EnioMDMPH** [comment]
Big fan of 3D slicer! but I was looking for more of a way to run it though the command line. Maybe I am not being descriptive enough (or you are maybe giving me too much credit), but when you say "Then you have to run TotalSegmentator", what is a step by step instructions on how to do that?

**Comment by SilasContaifer** [comment]
I undestand @EnioMDMPH issue, not everyone will know how to create a Virtual Environment.

And for me although I have created a Environment with a Python 3.7, with NumPy and the Pytorch (for CUDA 11.7, the same version that I know that works in my PC, using `conda`) and after that pip installing TotalSegmentator, I don't know how to properly use the following command: `TotalSegmentator -i ct.nii.gz -o segmentations`

As @wasserth  said I converted a  "_DICOM to nifti using e.g. the dcm2niix library_" (I also try using the [example_ct.nii.gz](https://github.com/wasserth/TotalSegmentator/blob/master/tests/reference_files/example_ct.nii.gz) from this [reference_files](https://github.com/wasserth/TotalSegmentator/tree/master/tests/reference_files) and renaming to ct.nii.gz) but when I execute this line in my Windows PowerShell: `TotalSegmentator -i ct.nii.gz -o segmentations` the result are the same as I just use this `TotalSegmentator` it shows me a list of Softwares and if I select anyone it will load the file **TotalSegmentator** from my virtual environment **Script** folder.

**Comment by lassoan** [comment]
> not everyone will know how to create a Virtual Environment

If someone wants to use TotalSegmentator engine directly then we can require very basic knowledge, such as how to create a virtual Python environment. Those who do not want to know about virtual Python environments can use TotalSegmentator in higher-level frameworks, such as 3D Slicer.

> And for me although I have created a Environment with a Python 3.7

Python 3.7 is very old. The [last bugfix release was 3 years ago](https://peps.python.org/pep-0537/#lifespan). I would recommend to use at least Python 3.9, otherwise you may run into issues.

> when I execute this line **TotalSegmentator -i ct.nii.gz -o segmentations** in my Windows PowerShell (that I run as an administrator) the result are the same as I just use this TotalSegmentator it shows me a software list

On Windows, shebang (`#!/usr/bin/env python` line at the beginning of a file) is not a thing. Instead, you need to run the script using the appropriate interpreter - in this case Python - like this:

    path/to/python.exe path/to/TotalSegmentator -i ...

**Comment by EnioMDMPH** [comment]
I was able to create a virtual environment, but when I went to "pip install totalsegmentator" I receive this error:
 
ERROR: Cannot install totalsegmentator==1.2, totalsegmentator==1.3 and totalsegmentator==1.4.0 because these package versions have conflicting dependencies.
The conflict is caused by:
    totalsegmentator 1.4.0 depends on SimpleITK==2.0.2
    totalsegmentator 1.3 depends on SimpleITK==2.0.2
    totalsegmentator 1.2 depends on SimpleITK==2.0.2

I subquently tried to "pip install totalsegmentator==1.5.0" and got this error: 

ERROR: Ignored the following versions that require a different python version: 1.21.2 Requires-Python >=3.7,<3.11; 1.21.3 Requires-Python >=3.7,<3.11; 1.21.4 Requires-Python >=3.7,<3.11; 1.21.5 Requires-Python >=3.7,<3.11; 1.21.6 Requires-Python >=3.7,<3.11; 1.6.2 Requires-Python >=3.7,<3.10; 1.6.3 Requires-Python >=3.7,<3.10; 1.7.0 Requires-Python >=3.7,<3.10; 1.7.0rc1 Requires-Python >=3.7,<3.10; 1.7.0rc2 Requires-Python >=3.7,<3.10; 1.7.1 Requires-Python >=3.7,<3.10; 1.7.2 Requires-Python >=3.7,<3.11; 1.7.3 Requires-Python >=3.7,<3.11; 1.8.0 Requires-Python >=3.8,<3.11; 1.8.0rc1 Requires-Python >=3.8,<3.11; 1.8.0rc2 Requires-Python >=3.8,<3.11; 1.8.0rc3 Requires-Python >=3.8,<3.11; 1.8.0rc4 Requires-Python >=3.8,<3.11; 1.8.1 Requires-Python >=3.8,<3.11; 2.5.2 Requires-Python !=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,<3.9dev,>=2.7
ERROR: Could not find a version that satisfies the requirement torch>=1.6.0a (from nnunet-customized) (from versions: none)
ERROR: No matching distribution found for torch>=1.6.0a


Currently running Python 3.11.2
Any suggestions? Also wondering if I should have started a new "problems installing thread"
