### ISSUE TITLE
Sternum segmentation not included

### ISSUE THREAD

**Issue by allemangD** [wasserth/TotalSegmentator#75]
The [class list in the README](https://github.com/wasserth/TotalSegmentator/blob/master/README.md?plain=1#L263) includes the sternum, which indicated to me that the sternum would be included in the segmentation output.

However it is not, and it doesn't appear in any demonstration images. I looked at the training data and see that there are no sternum segmentations there, either... after all, I wouldn't expect the model to segment the sternum if it has not been trained to.

Are/were there plans to segment the sternum? Is there any potential training data available which includes manual sternum segmentations?

**Comment by wasserth** [comment]
I am currently preparing the Sternum model. Therefore it already occurs in parts of the code but the weights are not ready yet.

**Comment by wasserth** [comment]
the sternum is available in TotalSegmentator v2 now.
