### ISSUE TITLE
poor segmentation results

### ISSUE THREAD

**Issue by ShefaaSaied** [wasserth/TotalSegmentator#78]
I've a problem with the segmentation results. results are very random and I don't think the inference is working properly.
the shape of the data is 512x512x186 with 1mm pixel spacing, min and max values are -2000 and  4095.

 Is there any preprocessing step I should do beforehand like clipping the dynamic range, cropping, rotating, .. ?

Here is a snapshot of the segmentation mask result using MITK
![Screenshot from 2023-02-20 15-50-27](https://user-images.githubusercontent.com/36079010/220127396-040a4673-565a-4372-aef1-08227bb69fa6.png)

**Comment by wasserth** [comment]
This segmentation result definitely looks wrong.  
On first look it seems that the patient is not laying on his back. This is a untypical image orientation. Orientation should look like in the following screenshot. You might have to flip some of the axis to make it have the same orientation.
![Screenshot from 2023-02-22 09-19-44](https://user-images.githubusercontent.com/26226563/220562727-a53967af-0e38-4a89-a413-4136cf3595b3.png)
