### ISSUE TITLE
Overlapped labels

### ISSUE THREAD

**Issue by Fivethousand5k** [wasserth/TotalSegmentator#8]
Hi, I just found that there are overlapped labels in your dataset, which means a voxel could be assigned with more than one classes.
For example, `./s0000/segmentations/hip_left.nii.gz` and `./s0000/segmentations/urinary_bladder.nii.gz`, there are re-labeled voxels in these segmentation files. And here is a picture of the overlapped region (where the red voxels denote the urinary_bladder while the green ones represent the hip_left): 
![image](https://user-images.githubusercontent.com/38652084/185914349-89b7daad-367f-466c-9b16-99034e79033d.png)

But for the nnUNet pipeline, I have to ensemble all of the given segmentation files (104 in total for a sample) into a single label file with values ranging from 0 to 104. How should I assign labels to these **overlapped voxels**?

**Comment by wasserth** [comment]
I use the dictrionary `class_map` in https://github.com/wasserth/TotalSegmentator/blob/master/totalsegmentator/map_to_binary.py to generate the label file for the nnUNet. Later labels will overwrite earlier labels (so in this case urinary bladder will overwrite hip_left).
