### ISSUE TITLE
TypeError: nnUNet_predict_image() got an unexpected keyword argument 'roi_subset'

### ISSUE THREAD

**Issue by beihaiyou** [wasserth/TotalSegmentator#80]
When I try "TotalSegmentator -i ct.nii.gz -o segmentations", TypeError in title happens. I have followed your README and installed TotalSegmentator. Could you please give me some helps

**Comment by wasserth** [comment]
Which version of TotalSegmentator have you installed?

**Comment by beihaiyou** [comment]
TotalSegmentator   1.5.2

**Comment by wasserth** [comment]
Can you try to install the latest master

pip install git+https://github.com/wasserth/TotalSegmentator.git

**Comment by beihaiyou** [comment]
thank you so much, I will have a try.
In fact, I delete this keyword roi_subset in nnUNet_predict_image(), and it doesn't report an error. I don't know if it will affect the result?
