### ISSUE TITLE
run TotalSegmentator from jupyter-slicer and/or from jupyter classic notebook

### ISSUE THREAD

**Issue by hubelef** [wasserth/TotalSegmentator#81]
Hello,
thank you very much for the quality of totalsegmentator. I can use it in slicer3D or in terminal (with more options like --ml or selected label list).
I would like to make batch processing of multiple scans. I can do it with jupyter and use ! command (or subprocess.run). But I would like to use classic python module import and jupyter with slicer kernel and classic python kernel. I use the options --ml and sometimes --fast
Can you please give example code for :
1. use TotalSegmentator from the jupyter-slicer notebook
2. use TotalSegmentator from classic jupyter notebook (with classic python kernel)
I guess the beginning like 'import totalsegmentator' which works but I don't know the next steps.
Regards,
Fabrice

**Comment by wasserth** [comment]
So far this is not easily possible. I will see if I can built a nicer python interface.

**Comment by hubelef** [comment]
Thank you for your response,
I will use it with 'subprocess.run'.

Also, I have tried the -rs (roi set) option without success : how (in terminal) can I choose a restricted list of tag (for example only the lung lobes and/or liver and/or only my bones_list). Can you please help me (I have installed TotalSegmentator two weeks ago and the -rs option was marked as comments).

**Comment by hubelef** [comment]
Also, last question please : I would like to run TotalSegmentator in Slicer3d from an usbkey. It works fine. But the computer is offline and TotalSegmentator downloads at the beginning of the process : how can I run TotalSegmentator without Internet ?

**Comment by wasserth** [comment]
With the newest version of TotalSegmentator (v1.5.3) you can use the following function to copy the manually downloaded weights to the correct folder:
```
totalseg_import_weights -i my_downloaded_weights.zip
```

**Comment by wasserth** [comment]
The newest version now also has a python interface: https://github.com/wasserth/TotalSegmentator#python-api

**Comment by hubelef** [comment]
Thank you so much, yes, the beautiful api is working fine.
I don't know why but from my jupyter-lab notebook, it tooks 45 min (instead of 6 min from the terminal command line with the same options)

**Comment by lixiaoqingnnz** [comment]
Hi. @wasserth 
I need to download all the weights first cause my computer is offline. However, for task 200,201,417,278,435. The download link can not be found in  https://github.com/wasserth/TotalSegmentator/blob/master/totalsegmentator/libs.py#L75
How should I do with it?
Many thanks

**Comment by wasserth** [comment]
So far those model are not available. I already integrated some code for them. They will come in the next major release.

**Comment by lixiaoqingnnz** [comment]
I see, thank you so much!
