### ISSUE TITLE
About Training Question

### ISSUE THREAD

**Issue by lisherlock** [wasserth/TotalSegmentator#84]
Thank you for your outstanding work! When training each submodel using nnUNet, may I ask if you only use the foreground data for training, or do you use all the data every time? Additionally, is the reason you chose epoch=4000 because you compared all possibilities and found that this model has the best performance? Looking forward to your reply!

**Comment by wasserth** [comment]
Not sure if I understand correctly what you mean by foreground data. But generally speaking for training we use the foreground data.
We evaluated that ep=4000 works a bit better than ep=1000. We did not evaluate other settings.

**Comment by lisherlock** [comment]
> Not sure if I understand correctly what you mean by foreground data. But generally speaking for training we use the foreground data. We evaluated that ep=4000 works a bit better than ep=1000. We did not evaluate other settings.
Thank you for your answer！
