### ISSUE TITLE
unrecognized arguments: --roi_subset

### ISSUE THREAD

**Issue by ajgong1** [wasserth/TotalSegmentator#85]
"TotalSegmentator: error: unrecognized arguments: --roi_subset liver" when using the docker image provided ( version master)

--roi_subset argument seems to work intermittently for me, but less than half the time
rerunning TotalSegmentator on the same file, but without the roi_subset argument still produces an output file that includes liver. 

Thanks so much for your help!

**Comment by marwanabb** [comment]
I'm faced with the same issue by using pip install

**Comment by wasserth** [comment]
I released a new version v1.5.3
Can you try it with that? 
`pip install --upgrade totalsegmentator`

**Comment by hubelef** [comment]
Hello, with v1.5.3 , -rs or --roi_subset option works very good for me (output directory with one file per class). But when I use also the -ml option, all the classes are present in my nifti output file. 
Is there a way to get an unique output nifti file with the --roi_subset option ?
Thank you for what you do

**Comment by wasserth** [comment]
This does not work unfortunately. You will have to remove all the other classes yourself from the multilabel file.

**Comment by wasserth** [comment]
the newest version will only contain the classes in the multilabel file which were specified in roi_subset
