### ISSUE TITLE
output in .obj file

### ISSUE THREAD

**Issue by AnandMulay** [wasserth/TotalSegmentator#86]
does Totalsegmnetator create a 3D output in .obj format?

**Comment by wasserth** [comment]
No, only nifti files

**Comment by AnandMulay** [comment]
Thanks @wasserth,  also I was giving a try to an online version that is totalsegmentor.com, but many times zip file stuck on upload, and nothing happened after that, is there something I'm missing in it?

**Comment by wasserth** [comment]
For big images (e.g. >50MB) the online version does not work very stable. How big were your images? And what is inside of the zip file? One Dicom image or several dicom images? You could send me one of those zip files which gets stuck. Then I can try to reproduce the issue.

**Comment by AnandMulay** [comment]
> For big images (e.g. >50MB) the online version does not work very stable. How big were your images? And what is inside of the zip file? One Dicom image or several dicom images? You could send me one of those zip files which gets stuck. Then I can try to reproduce the issue.

I tried a zip file contains DICOM Images, I reduced the size of the file by deleting a few images before it was 60mb then finally it is 20mb now, please have a look 
[BB.zip](https://github.com/wasserth/TotalSegmentator/files/10940068/BB.zip)

**Comment by AnandMulay** [comment]
alright now its working fine, yesterday when I was trying nothing happened.

**Comment by wasserth** [comment]
For me your zip file is also working when I try it right now

**Comment by AnandMulay** [comment]
> For me your zip file is also working when I try it right now

https://filebin.net/unehep8txptq8k29
Please give a try to full study, it doesn't work for me.

and Thanks for your prompt support :)

**Comment by wasserth** [comment]
I did not have time at the weekend to look at the file and now it is no longer available. Could you upload the full study again?

**Comment by AnandMulay** [comment]
> I did not have time at the weekend to look at the file and now it is no longer available. Could you upload the full study again?

strange it still works for me, but here is another upload of it - https://filebin.net/r7yqc1jog6r059iw

**Comment by wasserth** [comment]
This is still not working for me. It does not open any site when clicking on the link :(

**Comment by AnandMulay** [comment]
> This is still not working for me. It does not open any site when clicking on the link :(

probably that filebin is blocked on your side, try this: https://we.tl/t-INRQLZN3yp

**Comment by wasserth** [comment]
Now the download worked. Thank you!
