### ISSUE TITLE
Default number of preprocessing steps can drastically slowdown segmentation

### ISSUE THREAD

**Issue by vigsivan** [wasserth/TotalSegmentator#87]
When running TotalSegmentator on a machine with fewer cpu cores, preprocessing drastically slows down the segmentation process. Manually setting `num_threads_preprocessing` in `nnUnet_predict`  to a number smaller than 6 is able to drastically speed up processing in this scenario, but it would be great if this option were exposed through the cli.

Thanks for this amazing project!

**Comment by wasserth** [comment]
Thanks for this hint. I just pushed a commit which makes this controllable with the parameters `--nr_thr_resamp` and `--nr_thr_saving`.
