### ISSUE TITLE
Spine segmentation format

### ISSUE THREAD

**Issue by louisblankemeier** [wasserth/TotalSegmentator#88]
Hi Jakob,

Thanks for your awesome work! I was wondering how you label the vertebrae. Do you forgo labeling transitional vertebrae (T13, L6), leaving some vertebrae without labels, or do you count up from the sacrum starting with L5 until you get to C1? 

Thanks a lot!

**Comment by wasserth** [comment]
Transitional vertebrae are not labeled. So if a patient should have SWK1/L6 then we would skip this and then we would start counting with L5. If a subject should have one additional Cervical vertebrae then this is also skipped. I think we did not have any cases with T13 in our training dataset.
We are currently working on segmentation of SWK1.
