### ISSUE TITLE
Memory Requirements

### ISSUE THREAD

**Issue by ChristianHinge** [wasserth/TotalSegmentator#89]
I am running into problems with insufficient GPU memory.

Systeminfo
Titan RTX 24GB GPU memory, 132 GB Physical memory

Image size: 400, 400, 928

Running both with and without the `--fast` option cause a `torch.cuda.OutOfMemoryError` during prediction. I have been monitoring the GPU usage with `nvidia-smi` during runtime to ensure that no other processes occupy the memory. The program just barely manages  to stay within the 24gb when running with both `--fast --body_seg`, When comparing the image size with those in the `README` and the accompanying expected memory usage, I find it very odd that the program runs out of memory in any scenario. TotalSegmentator is installed in a fresh python3.8 environment. Any help or tips would be appreciated.

**Comment by wasserth** [comment]
This is indeed a bit strange. However, I do not really have an idea what might cause the high memory usage.
To reduce memory usage in general you can also try the option `--force_split`.
