### ISSUE TITLE
Error when saving single nifti file 

### ISSUE THREAD

**Issue by deepakri201** [wasserth/TotalSegmentator#9]
Hi, 

I am trying to create a single label map using the command:

`!TotalSegmentator -i input.nii.gz -o output.nii.gz --ml --fast `

The `output.nii` successfully saves out, but I get the following error: 

![image](https://user-images.githubusercontent.com/59979551/186496632-f056bc27-94a4-462c-86af-e750d5fdecfc.png)

Thank you!

**Comment by joshy** [comment]
Hi deepakri201,

thanks for trying out. Indeed that is a error. As a temporary fix, you don't need to as the ouput is saved, you could paste the following lines
```
img = nib.load(tmp_dir / "s01.nii.gz")
img_data = img.get_fdata()
```
in the file `nnunet.py` at: `/usr/local/lib/python3.7/dist-packages/totalsegmentator/nnunet.py` after line number `194`. Then the error should disappear. We will release a new version next week with a fix. Thanks for letting us know.

**Comment by wasserth** [comment]
I just pushed the fix to the master branch. We will release a new version to pip soon. Until then you can directly install from the lastest master branch with the following command:
```
pip install git+https://github.com/wasserth/TotalSegmentator.git
```
