### ISSUE TITLE
Can't upload dataset in time, the network is cut off

### ISSUE THREAD

**Issue by liududu** [wasserth/TotalSegmentator#91]
I want to have a try by using the online version of this tool. But I was not able to upload my dataset in time, then the connection was cut off. The size of my dataset is around 60MB and my average upload speed is 1.3MB/s. Total size of upload data always stucks at around 40MB. 

Then with further investigation, I found that there is a "timeout" setting in the "dropzone.js"  located in the npm dir. I was thinking that increasing this value can solve this problem. Could you please check out? Thanks a lot.

**Comment by liududu** [comment]
@wasserth The default XHR timeout is set to 30s, so I can't upload relatively large file to the website.

**Comment by joshy** [comment]
Hi, I can have a look into it.

**Comment by wasserth** [comment]
Or maybe it is better to set it in the settings in `index.html`. Not sure.

**Comment by joshy** [comment]
I have increased the timeout to 5min. Please check @liududu.

**Comment by liududu** [comment]
Confirmed，Successfully Upload，thanks for your work!
