### ISSUE TITLE
ct.nii.gz of s0864 in the dataset cannot be unzipped due to file corruption.

### ISSUE THREAD

**Issue by Ruikun-Li** [wasserth/TotalSegmentator#92]
I downloaded the dataset from  Zenodo twice, but the ct.nii.gz of s0864 in the dataset could not be unzipped due to file corruption.
Is there a problem with the source file? Or whether I can get the ct.nii.gz of s0864 by other means.
Hope to receive you reply. Thank you very much!
![image](https://user-images.githubusercontent.com/31624867/228704724-f1f535dc-22bc-4d47-a585-eb8e066dfa8f.png)

**Comment by wasserth** [comment]
Unfortunately this file is indeed corrupted. You have to exclude it. In the next release of the dataset this will be fixed.

**Comment by Ruikun-Li** [comment]
Thank you! Look forward to the new version of the dataset and thanks for your excellent project again.

**Comment by wasserth** [comment]
the new version of the dataset is online now.
