### ISSUE TITLE
path to download rordenlab/dcm2niix arm64 outdated

### ISSUE THREAD

**Issue by fohofmann** [wasserth/TotalSegmentator#95]
Hi Jakob,

thank you for all your efforts.

# Problem
The links in `dicom_io.py` ([L23](https://github.com/wasserth/TotalSegmentator/blob/10745f7ee566b0a5b4b524a725feab3bf6c1925c/totalsegmentator/dicom_io.py#L23)) to the arm64 / Mac version of [rordenlab/dcm2niix](https://github.com/rordenlab/dcm2niix) are not working anymore.

# Solution
The link should be updated to `https://github.com/rordenlab/dcm2niix/releases/latest/download/macos_dcm2niix.pkg`. For Reference see [here](https://github.com/rordenlab/dcm2niix/releases/tag/v1.0.20220720).

Temporary and quick solution:
- load dcm2niix manually to environment
- comment out [L54-58](https://github.com/wasserth/TotalSegmentator/blob/10745f7ee566b0a5b4b524a725feab3bf6c1925c/totalsegmentator/dicom_io.py#L54-58)
```python
#    config_dir = get_config_dir()
#    dcm2niix = config_dir / "dcm2niix"

#    if not dcm2niix.exists():
#        download_dcm2niix()
```
- use dcm2niix directly [L60](https://github.com/wasserth/TotalSegmentator/blob/10745f7ee566b0a5b4b524a725feab3bf6c1925c/totalsegmentator/dicom_io.py#L60):
```python
    subprocess.call(f"dcm2niix -o {output_path.parent} -z y -f {output_path.name[:-7]} {input_path} {verbose_str}", shell=True)
```

# To discuss
I did not fork and PR these changes directly due to the following considerations:
- I am not sure, whether the `macos_dcm2niix.pkg`-pkg works in both, arm64 and x86_64 environments and have only the option to test it at arm64 (working). If it works also for  x86_64, we could get rid of the differentiation in [L24](https://github.com/wasserth/TotalSegmentator/blob/10745f7ee566b0a5b4b524a725feab3bf6c1925c/totalsegmentator/dicom_io.py#L24).
- The loaded files are not *.zip, but *.pkg. Therefore, downloading `macos_dcm2niix.pkg` would break `zipfile.ZipFile` in [L36](https://github.com/wasserth/TotalSegmentator/blob/10745f7ee566b0a5b4b524a725feab3bf6c1925c/totalsegmentator/dicom_io.py#L36).
- I am not sure whether you prefer to keep `download_dcm2niix()`or want to add `dcm2niix` to the requirements.

Thank you again and all the best,
Felix

**Comment by wasserth** [comment]
Thanks for pointing this out. I changed the code and documentation: on MacOS automatic download of dcm2niix is no longer possible. You have to manually install dcm2niix now.
