### ISSUE TITLE
How to calculate the muscle and fat volume after muscle segmentation and export it from 3d Slicer to excel sheet

### ISSUE THREAD

**Issue by hasm200** [wasserth/TotalSegmentator#96]
Is there a tool to get the fat volume and separate it from the muscle volume? I have seen most of the questions in the forum do not specify one tool. For example in my project I am planning to segment rotator cuff muscles and determine the fat volume and muscle volume separately by CT scan. Then want to export the volume to an excel sheet.

If possible explain step by step for a beginner not have experience in coding.

Thank you

**Comment by wasserth** [comment]
There is not a specific tool for that. You would have to do that yourself.
