### ISSUE TITLE
Future Work on MRI Support?

### ISSUE THREAD

**Issue by tarolangner** [wasserth/TotalSegmentator#97]
Hi Jakob,

first of all congratulations to these results and the reception this project has rightfully received! 

This is not really about any issue at all, but rather a question: At Nvidia GTC earlier this Spring, someone mentioned plans for TotalSegmentator to also support MRI in the future. Do you perhaps have any update or thoughts to share on this?

Best regards

**Comment by wasserth** [comment]
Extending TotalSegmentator to MRI is on our agenda, but it will be more in the future. This will take at least another year.

**Comment by SamPIngram** [comment]
Jumping on this issue, to check my understanding. When talking about MRI support, is that model-availability support or the ability to use the framework to train a model on MRI data support? As TotalSegmentator is based on nnU-NET would the latter not already be supported? Or are there additional internals that have been tuned for CT?
