### ISSUE TITLE
Logo / icon?

### ISSUE THREAD

**Issue by kislinsk** [wasserth/TotalSegmentator#98]
Having assigned the task to come up with an icon for the TotalSegmentator segmentation tool in MITK I noticed that the project does not have a logo or - even better - a simple, recognizable icon that also works in smaller sizes.

Anything planned in that direction or any ideas how TotalSegmentator could be represented in this context? 👀

**Comment by wasserth** [comment]
So far TotalSegmentator does not have a logo. You could use something similar to this:
https://media.licdn.com/dms/image/C4E22AQFNtzd1EpLtYA/feedshare-shrink_2048_1536/0/1676894876451?e=1682553600&v=beta&t=XwbpkqgvtAmQ1l2iK6npIj1uPDukSwEA5Qbvi1dpYeg
